import type { Banner, Category, Product } from "./types";

export const CATEGORIES: Category[] = [
  {
    id: "cat-panelas",
    name: "Panelas",
    slug: "panelas",
    description: "Jogos de panelas antiaderentes, cerâmica e inox, frigideiras, caçarolas, woks e chaleiras.",
    image_url: "https://images.unsplash.com/photo-1556910103-1c02745aae4d?auto=format&fit=crop&w=800&q=80",
    position: 1,
  },
  {
    id: "cat-pressao",
    name: "Panelas de Pressão",
    slug: "panelas-de-pressao",
    description: "Panelas de pressão com fechamento externo, interno e linha cerâmica antiaderente.",
    image_url: "https://images.unsplash.com/photo-1585515320310-259814833e62?auto=format&fit=crop&w=800&q=80",
    position: 2,
  },
  {
    id: "cat-eletro",
    name: "Eletroportáteis",
    slug: "eletroportateis",
    description: "Panelas de pressão elétricas digitais e cooktops de indução portáteis.",
    image_url: "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=800&q=80",
    position: 3,
  },
  {
    id: "cat-lixeiras",
    name: "Lixeiras",
    slug: "lixeiras",
    description: "Lixeiras com pedal em inox, basculantes, com sensor de movimento e para coleta seletiva.",
    image_url: "https://images.unsplash.com/photo-1585914924626-15adac1e6402?auto=format&fit=crop&w=800&q=80",
    position: 4,
  },
  {
    id: "cat-utensilios",
    name: "Utensílios de Cozinha",
    slug: "utensilios-de-cozinha",
    description: "Kits de silicone alimentício, aço inox 18/10, tábuas de corte em bambu e escorredores.",
    image_url: "https://images.unsplash.com/photo-1565114616849-60c2f5ef9df7?auto=format&fit=crop&w=800&q=80",
    position: 5,
  },
  {
    id: "cat-mesa",
    name: "Mesa & Talheres",
    slug: "mesa-e-talheres",
    description: "Faqueiros completos em inox, bandejas de servir, bowls e porta-guardanapos.",
    image_url: "https://images.unsplash.com/photo-1573821663912-569905455b1c?auto=format&fit=crop&w=800&q=80",
    position: 6,
  },
  {
    id: "cat-assadeiras",
    name: "Assadeiras & Formas",
    slug: "assadeiras-e-formas",
    description: "Assadeiras antiaderentes, formas de bolo redondas, para lasanha e para pão.",
    image_url: "https://images.unsplash.com/photo-1555949258-eb67b1ef0ceb?auto=format&fit=crop&w=800&q=80",
    position: 7,
  },
  {
    id: "cat-organizacao",
    name: "Organização",
    slug: "organizacao",
    description: "Porta-temperos giratórios, potes herméticos em acrílico crystal e organizadores de pia.",
    image_url: "https://images.unsplash.com/photo-1493606278519-11aa9f86e40a?auto=format&fit=crop&w=800&q=80",
    position: 8,
  },
  {
    id: "cat-churrasco",
    name: "Churrasco",
    slug: "churrasco",
    description: "Kits de churrasco com maleta, grelhas argentinas em inox e churrasqueiras portáteis.",
    image_url: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=800&q=80",
    position: 9,
  },
];

export const BANNERS: Banner[] = [
  {
    id: "banner-1",
    title: "Antiaderente cerâmico que dura anos",
    subtitle: "Linha Ceramic Pro com fundo triplo, revestimento cerâmico livre de PFOA e compatibilidade total com indução.",
    eyebrow: "LINHA CERAMIC PRO",
    cta_label: "Ver panelas",
    cta_url: "/categoria/panelas",
    image_url: "https://images.unsplash.com/photo-1556910103-1c02745aae4d?auto=format&fit=crop&w=1600&q=80",
    position: 1,
    active: true,
  },
  {
    id: "banner-2",
    title: "Pressão com segurança máxima",
    subtitle: "Panelas de pressão Nexlar com 5 sistemas de segurança, aço inox 18/10 e compatíveis com todos os tipos de fogão.",
    eyebrow: "PANELAS DE PRESSÃO",
    cta_label: "Ver panelas de pressão",
    cta_url: "/categoria/panelas-de-pressao",
    image_url: "https://images.unsplash.com/photo-1585515320310-259814833e62?auto=format&fit=crop&w=1600&q=80",
    position: 2,
    active: true,
  },
  {
    id: "banner-3",
    title: "Sua cozinha limpa e organizada",
    subtitle: "Porta-temperos, potes herméticos, lixeiras em inox com pedal e organizadores com design premium.",
    eyebrow: "ORGANIZAÇÃO & HIGIENE",
    cta_label: "Explorar organização",
    cta_url: "/categoria/organizacao",
    image_url: "https://images.unsplash.com/photo-1556228578-8c89e6adf883?auto=format&fit=crop&w=1600&q=80",
    position: 3,
    active: true,
  },
];

export const PRODUCTS: Product[] = [
  // ================= PANELAS =================
  {
    id: "prod-pan-01",
    name: "Jogo de Panelas Nexlar Ceramic Pro 5 Peças Antiaderente",
    slug: "jogo-panelas-ceramic-pro-5pc",
    sku: "NX-PAN-001",
    short_description: "Jogo completo com antiaderente cerâmico livre de PFOA e fundo de indução.",
    description: "O Jogo de Panelas Nexlar Ceramic Pro é a escolha ideal para cozinhar com praticidade e saúde. Fabricado em alumínio forjado com revestimento cerâmico de alta durabilidade, distribui o calor uniformemente e não gruda alimentos. Acompanha tampas de vidro temperado com saída de vapor.",
    category_id: "cat-panelas",
    categories: { name: "Panelas", slug: "panelas" },
    price: 389.90,
    compare_at_price: 489.90,
    pix_discount_percent: 10,
    stock: 50,
    rating: 4.9,
    reviews_count: 234,
    free_shipping: true,
    featured: true,
    is_new: false,
    active: true,
    created_at: "2026-09-10T10:00:00Z",
    highlights: ["Revestimento cerâmico livre de PFOA", "Compatível com fogão de indução e a gás", "Tampas de vidro temperado", "Cabos com toque suave antiaquecimento"],
    specs: { "Peças": "5 (caçarola 24cm, panela 20cm, panela 18cm, frigideira 24cm, fervedor 14cm)", "Material": "Alumínio forjado com revestimento cerâmico", "Garantia": "2 anos", "Lava-louças": "Sim" },
    product_images: [
      { id: "img-pan-01-1", url: "https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?auto=format&fit=crop&w=1000&q=80", alt: "Jogo de Panelas Nexlar Ceramic Pro 5 Peças", position: 0 },
      { id: "img-pan-01-2", url: "https://images.unsplash.com/photo-1556910103-1c02745aae4d?auto=format&fit=crop&w=1000&q=80", alt: "Conjunto Ceramic Pro na bancada", position: 1 },
    ],
  },
  {
    id: "prod-pan-02",
    name: "Jogo de Panelas Nexlar Inox Premium 7 Peças Fundo Triplo",
    slug: "jogo-panelas-inox-premium-7pc",
    sku: "NX-PAN-002",
    short_description: "Jogo em aço inox 18/10 com fundo triplo encapsulado para máxima performance.",
    description: "Elegância e durabilidade para a vida toda. O Jogo de Panelas Nexlar Inox Premium conta com fundo triplo que distribui o calor perfeitamente, cozinhando mais rápido e economizando gás e energia.",
    category_id: "cat-panelas",
    categories: { name: "Panelas", slug: "panelas" },
    price: 549.90,
    compare_at_price: 699.90,
    pix_discount_percent: 10,
    stock: 35,
    rating: 4.9,
    reviews_count: 187,
    free_shipping: true,
    featured: true,
    is_new: false,
    active: true,
    created_at: "2026-09-09T10:00:00Z",
    highlights: ["Aço inox 18/10 cirúrgico", "Fundo triplo encapsulado", "Não solta resíduos nos alimentos", "Compatível com todos os fogões"],
    specs: { "Peças": "7 peças completas", "Material": "Aço Inoxidável 18/10", "Fundo": "Triplo (aço + alumínio + aço)", "Garantia": "5 anos" },
    product_images: [
      { id: "img-pan-02-1", url: "https://images.unsplash.com/photo-1585515320310-259814833e62?auto=format&fit=crop&w=1000&q=80", alt: "Jogo de Panelas Nexlar Inox 7 Peças", position: 0 },
      { id: "img-pan-02-2", url: "https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=1000&q=80", alt: "Panelas inox acabamento espelhado", position: 1 },
    ],
  },
  {
    id: "prod-pan-03",
    name: "Jogo de Panelas Empilháveis Nexlar Loft 5 Peças Cabo Removível",
    slug: "jogo-panelas-empilhaveis-loft-5pc",
    sku: "NX-PAN-003",
    short_description: "Design modular com cabo removível. Economiza até 60% de espaço no armário.",
    description: "O Jogo Nexlar Loft foi projetado para cozinhas compactas e modernas. Seu cabo ergonômico removível permite usar as peças no fogão, levar direto ao forno e guardar empilhadas de forma organizada.",
    category_id: "cat-panelas",
    categories: { name: "Panelas", slug: "panelas" },
    price: 449.90,
    compare_at_price: 599.90,
    pix_discount_percent: 10,
    stock: 28,
    rating: 4.8,
    reviews_count: 156,
    free_shipping: true,
    featured: false,
    is_new: true,
    active: true,
    created_at: "2026-09-15T10:00:00Z",
    highlights: ["Cabo removível com trava de alta segurança", "Empilhamento inteligente compacto", "Pode ir direto ao forno sem o cabo", "Antiaderente cerâmico premium"],
    specs: { "Peças": "5 peças + 1 cabo intercambiável", "Revestimento": "Cerâmica antiaderente Pro", "Cor": "Areia / Off-white", "Garantia": "2 anos" },
    product_images: [
      { id: "img-pan-03-1", url: "https://images.unsplash.com/photo-1590794056226-79ef3a8147e1?auto=format&fit=crop&w=1000&q=80", alt: "Jogo de Panelas Empilháveis Nexlar Loft", position: 0 },
      { id: "img-pan-03-2", url: "https://images.unsplash.com/photo-1556910103-1c02745aae4d?auto=format&fit=crop&w=1000&q=80", alt: "Panelas empilhadas com cabo removível", position: 1 },
    ],
  },
  {
    id: "prod-pan-04",
    name: "Frigideira Antiaderente Nexlar Ceramic Pro 26cm",
    slug: "frigideira-antiaderente-ceramic-pro-26cm",
    sku: "NX-PAN-004",
    short_description: "Frigideira funda 26cm com revestimento cerâmico antiaderente livre de toxinas.",
    description: "Prepare ovos, grelhados, tapiocas e legumes sem precisar de óleo. A Frigideira Nexlar Ceramic Pro possui base reforçada que não deforma e cabo antitérmico para total conforto.",
    category_id: "cat-panelas",
    categories: { name: "Panelas", slug: "panelas" },
    price: 149.90,
    compare_at_price: 199.90,
    pix_discount_percent: 10,
    stock: 65,
    rating: 4.8,
    reviews_count: 143,
    free_shipping: false,
    featured: true,
    is_new: false,
    active: true,
    created_at: "2026-09-12T10:00:00Z",
    highlights: ["Diâmetro de 26cm com bordas altas", "Revestimento cerâmico de fácil limpeza", "Compatível com indução", "Cabo soft-touch"],
    specs: { "Diâmetro": "26 cm", "Capacidade": "2.2 Litros", "Material": "Alumínio 4.5mm com cerâmica", "Garantia": "1 ano" },
    product_images: [
      { id: "img-pan-04-1", url: "https://images.unsplash.com/photo-1534361960057-19f4434a4d4e?auto=format&fit=crop&w=1000&q=80", alt: "Frigideira Antiaderente Nexlar Ceramic Pro 26cm", position: 0 },
      { id: "img-pan-04-2", url: "https://images.unsplash.com/photo-1571167366136-b57e5ee84b27?auto=format&fit=crop&w=1000&q=80", alt: "Frigideira em uso no fogão", position: 1 },
    ],
  },
  {
    id: "prod-pan-05",
    name: "Caçarola Antiaderente Nexlar Ceramic Pro 24cm com Tampa",
    slug: "cacarola-antiaderente-ceramic-pro-24cm",
    sku: "NX-PAN-005",
    short_description: "Caçarola 24cm com alças de silicone e tampa de vidro com saída de vapor.",
    description: "Perfeita para preparar risotos, ensopados, carnes e molhos. A Caçarola Nexlar 24cm combina grande capacidade com o melhor antiaderente cerâmico do mercado.",
    category_id: "cat-panelas",
    categories: { name: "Panelas", slug: "panelas" },
    price: 169.90,
    compare_at_price: 219.90,
    pix_discount_percent: 10,
    stock: 55,
    rating: 4.7,
    reviews_count: 112,
    free_shipping: false,
    featured: false,
    is_new: false,
    active: true,
    created_at: "2026-09-08T10:00:00Z",
    highlights: ["Capacidade generosa de 4.2L", "Tampa de vidro temperado resistente a quedas", "Alças de silicone seguras", "Fundo de indução integrado"],
    specs: { "Diâmetro": "24 cm", "Capacidade": "4.2 Litros", "Compatibilidade": "Gás, elétrico, indução, vitrocerâmico", "Garantia": "1 ano" },
    product_images: [
      { id: "img-pan-05-1", url: "https://images.unsplash.com/photo-1526256262350-7da7584cf5eb?auto=format&fit=crop&w=1000&q=80", alt: "Caçarola Nexlar Ceramic Pro 24cm", position: 0 },
      { id: "img-pan-05-2", url: "https://images.unsplash.com/photo-1590794056226-79ef3a8147e1?auto=format&fit=crop&w=1000&q=80", alt: "Caçarola detalhe alças e tampa", position: 1 },
    ],
  },
  {
    id: "prod-pan-06",
    name: "Wok Antiaderente Nexlar Asian Chef 32cm com Tampa",
    slug: "wok-antiaderente-nexlar-asian-chef-32cm",
    sku: "NX-PAN-006",
    short_description: "Wok 32cm com formato oriental profundo para saltear legumes e carnes.",
    description: "Desenvolvida para saltear e cozinhar em altas temperaturas com agilidade. O formato cônico do Wok Nexlar distribui o calor de maneira rápida e uniforme.",
    category_id: "cat-panelas",
    categories: { name: "Panelas", slug: "panelas" },
    price: 199.90,
    compare_at_price: 259.90,
    pix_discount_percent: 10,
    stock: 45,
    rating: 4.7,
    reviews_count: 78,
    free_shipping: false,
    featured: false,
    is_new: false,
    active: true,
    created_at: "2026-09-07T10:00:00Z",
    highlights: ["Diâmetro amplo de 32cm", "Acompanha tampa de vidro", "Cabo longo ergonômico", "Antiaderente de alta durabilidade"],
    specs: { "Diâmetro": "32 cm", "Profundidade": "9.5 cm", "Capacidade": "4.8 Litros", "Garantia": "1 ano" },
    product_images: [
      { id: "img-pan-06-1", url: "https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&w=1000&q=80", alt: "Wok Antiaderente Nexlar Asian Chef 32cm", position: 0 },
      { id: "img-pan-06-2", url: "https://images.unsplash.com/photo-1586190848861-99aa4a171e90?auto=format&fit=crop&w=1000&q=80", alt: "Wok para preparo de receitas", position: 1 },
    ],
  },
  {
    id: "prod-pan-07",
    name: "Chaleira em Aço Inox Nexlar com Apito 2.2L",
    slug: "chaleira-aco-inox-com-apito-2-2l",
    sku: "NX-PAN-007",
    short_description: "Chaleira clássica com apito sonoro de fervura e cabo que não esquenta.",
    description: "A Chaleira Nexlar em Inox alia o charme tradicional do apito harmônico à eficiência do fundo triplo, aquecendo a água do café ou chá em poucos minutos.",
    category_id: "cat-panelas",
    categories: { name: "Panelas", slug: "panelas" },
    price: 119.90,
    compare_at_price: 159.90,
    pix_discount_percent: 10,
    stock: 60,
    rating: 4.8,
    reviews_count: 95,
    free_shipping: false,
    featured: false,
    is_new: false,
    active: true,
    created_at: "2026-09-06T10:00:00Z",
    highlights: ["Apito sonoro ao atingir fervura", "Aço inox escovado elegante", "Gatilho de abertura segura no cabo", "Compatível com indução"],
    specs: { "Capacidade": "2.2 Litros", "Material": "Aço Inox com cabo baquelite", "Compatibilidade": "Todos os tipos de fogão", "Garantia": "1 ano" },
    product_images: [
      { id: "img-pan-07-1", url: "https://images.unsplash.com/photo-1510774463633-28c33ef2c16d?auto=format&fit=crop&w=1000&q=80", alt: "Chaleira Inox Nexlar com Apito", position: 0 },
      { id: "img-pan-07-2", url: "https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=1000&q=80", alt: "Chaleira inox sobre o fogão", position: 1 },
    ],
  },

  // ================= PANELAS DE PRESSÃO =================
  {
    id: "prod-pre-01",
    name: "Panela de Pressão Nexlar Inox 4.5L Fechamento Externo",
    slug: "panela-pressao-inox-4-5l-fechamento-externo",
    sku: "NX-PRE-001",
    short_description: "Panela de pressão 4.5L em inox com 5 dispositivos de segurança certificados.",
    description: "Segurança total e rapidez no preparo de feijão, carnes de panela e sopas. Fabricada em aço inoxidável 18/10 com tampa de fechamento externo prático.",
    category_id: "cat-pressao",
    categories: { name: "Panelas de Pressão", slug: "panelas-de-pressao" },
    price: 249.90,
    compare_at_price: 319.90,
    pix_discount_percent: 10,
    stock: 45,
    rating: 4.9,
    reviews_count: 156,
    free_shipping: true,
    featured: true,
    is_new: false,
    active: true,
    created_at: "2026-09-11T10:00:00Z",
    highlights: ["5 sistemas independentes de segurança", "Fechamento externo rápido e seguro", "Fundo triplo para indução e gás", "Aço inox que não altera o sabor"],
    specs: { "Capacidade": "4.5 Litros", "Pressão de trabalho": "80 kPa", "Material": "Aço Inox 18/10", "Garantia": "5 anos" },
    product_images: [
      { id: "img-pre-01-1", url: "https://images.unsplash.com/photo-1595587637401-83ff822bd63b?auto=format&fit=crop&w=1000&q=80", alt: "Panela de Pressão Nexlar Inox 4.5L", position: 0 },
      { id: "img-pre-01-2", url: "https://images.unsplash.com/photo-1585515320310-259814833e62?auto=format&fit=crop&w=1000&q=80", alt: "Válvulas de segurança panela de pressão", position: 1 },
    ],
  },
  {
    id: "prod-pre-02",
    name: "Panela de Pressão Antiaderente Nexlar Ceramic Pressure 4.2L",
    slug: "panela-pressao-antiaderente-ceramic-pressure-4-2l",
    sku: "NX-PRE-002",
    short_description: "Pressão com antiaderente cerâmico interno. Nada gruda no fundo.",
    description: "A revolução na cozinha: cozinhe sob pressão com a praticidade da limpeza do antiaderente cerâmico. Ideal para quem busca rapidez e facilidade de limpeza.",
    category_id: "cat-pressao",
    categories: { name: "Panelas de Pressão", slug: "panelas-de-pressao" },
    price: 329.90,
    compare_at_price: 419.90,
    pix_discount_percent: 10,
    stock: 30,
    rating: 4.9,
    reviews_count: 98,
    free_shipping: true,
    featured: true,
    is_new: true,
    active: true,
    created_at: "2026-09-14T10:00:00Z",
    highlights: ["Interior com cerâmica antiaderente", "Não gruda feijão nem queima no fundo", "Fechamento externo inteligente", "Compatível com fogões de indução"],
    specs: { "Capacidade": "4.2 Litros", "Revestimento interno": "Ceramic Life Pro", "Cor": "Areia com tampa inox", "Garantia": "2 anos" },
    product_images: [
      { id: "img-pre-02-1", url: "https://images.unsplash.com/photo-1556910103-1c02745aae4d?auto=format&fit=crop&w=1000&q=80", alt: "Panela de Pressão Ceramic Pressure Nexlar", position: 0 },
      { id: "img-pre-02-2", url: "https://images.unsplash.com/photo-1595587637401-83ff822bd63b?auto=format&fit=crop&w=1000&q=80", alt: "Tampa de fechamento cerâmica", position: 1 },
    ],
  },
  {
    id: "prod-pre-03",
    name: "Panela de Pressão Nexlar Vapt Fechamento Interno 4.5L",
    slug: "panela-pressao-vapt-fechamento-interno-4-5l",
    sku: "NX-PRE-003",
    short_description: "Sistema tradicional de fechamento interno seguro e ultra vedação.",
    description: "A clássica panela de pressão com sistema interno reforçado em alumínio polido de espessura grossa com válvula de alívio contínuo.",
    category_id: "cat-pressao",
    categories: { name: "Panelas de Pressão", slug: "panelas-de-pressao" },
    price: 189.90,
    compare_at_price: 239.90,
    pix_discount_percent: 10,
    stock: 50,
    rating: 4.7,
    reviews_count: 112,
    free_shipping: false,
    featured: false,
    is_new: false,
    active: true,
    created_at: "2026-09-05T10:00:00Z",
    highlights: ["Fechamento interno clássico", "Alumínio espesso de alta resistência", "Válvula de silicone de segurança extra", "Pegador anatômico"],
    specs: { "Capacidade": "4.5 Litros", "Material": "Alumínio reforçado", "Garantia": "2 anos" },
    product_images: [
      { id: "img-pre-03-1", url: "https://images.unsplash.com/photo-1595587637401-83ff822bd63b?auto=format&fit=crop&w=1000&q=80", alt: "Panela de Pressão Nexlar Vapt 4.5L", position: 0 },
      { id: "img-pre-03-2", url: "https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=1000&q=80", alt: "Panela de pressão fechamento interno", position: 1 },
    ],
  },

  // ================= ELETROPORTÁTEIS =================
  {
    id: "prod-ele-01",
    name: "Panela de Pressão Elétrica Digital Nexlar Master Chef 5L",
    slug: "panela-pressao-eletrica-digital-master-chef-5l",
    sku: "NX-ELE-001",
    short_description: "12 programas automáticos pré-definidos com display digital e timer programável.",
    description: "Praticidade absoluta: coloque os ingredientes, aperte um botão e saia de casa. A Panela de Pressão Elétrica Nexlar desliga sozinha e mantém a comida aquecida até a hora de servir.",
    category_id: "cat-eletro",
    categories: { name: "Eletroportáteis", slug: "eletroportateis" },
    price: 599.90,
    compare_at_price: 799.90,
    pix_discount_percent: 10,
    stock: 25,
    rating: 4.9,
    reviews_count: 203,
    free_shipping: true,
    featured: true,
    is_new: false,
    active: true,
    created_at: "2026-09-13T10:00:00Z",
    highlights: ["12 funções inteligentes na tela touch", "Timer programável com até 24h de antecedência", "Super silenciosa e sem cheiro", "Cuba antiaderente removível"],
    specs: { "Capacidade": "5.0 Litros", "Potência": "1000W", "Voltagem": "110V / 220V", "Garantia": "2 anos" },
    product_images: [
      { id: "img-ele-01-1", url: "https://images.unsplash.com/photo-1556909212-d5b604d0c90d?auto=format&fit=crop&w=1000&q=80", alt: "Panela de Pressão Elétrica Digital Nexlar 5L", position: 0 },
      { id: "img-ele-01-2", url: "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=1000&q=80", alt: "Painel touch panela elétrica", position: 1 },
    ],
  },
  {
    id: "prod-ele-02",
    name: "Cooktop Portátil de Indução Nexlar Slim 1 Boca 2200W",
    slug: "cooktop-portatil-inducao-slim-1-boca-2200w",
    sku: "NX-ELE-002",
    short_description: "Cooktop de indução ultra fino com 9 níveis de potência e trava de segurança infantil.",
    description: "Cozinhe em qualquer lugar com eficiência máxima. O Cooktop de Indução Nexlar ferve água na metade do tempo do gás e sua superfície de vidro cerâmico esfria imediatamente ao retirar a panela.",
    category_id: "cat-eletro",
    categories: { name: "Eletroportáteis", slug: "eletroportateis" },
    price: 299.90,
    compare_at_price: 399.90,
    pix_discount_percent: 10,
    stock: 35,
    rating: 4.8,
    reviews_count: 145,
    free_shipping: true,
    featured: true,
    is_new: false,
    active: true,
    created_at: "2026-09-12T10:00:00Z",
    highlights: ["2200W de potência de resposta imediata", "Mesa vitrocerâmica de facílima limpeza", "Sensor automático de presença de panela", "Timer integrado até 180 min"],
    specs: { "Potência": "2200W", "Níveis de temperatura": "60°C a 240°C", "Dimensões": "28 x 35 x 4.5 cm", "Garantia": "1 ano" },
    product_images: [
      { id: "img-ele-02-1", url: "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=1000&q=80", alt: "Cooktop de Indução Portátil Nexlar 1 Boca", position: 0 },
      { id: "img-ele-02-2", url: "https://images.unsplash.com/photo-1556909212-d5b604d0c90d?auto=format&fit=crop&w=1000&q=80", alt: "Cooktop indução painel digital", position: 1 },
    ],
  },

  // ================= LIXEIRAS =================
  {
    id: "prod-lix-01",
    name: "Lixeira em Aço Inox com Pedal Nexlar 20L Amortecedor Soft-Close",
    slug: "lixeira-aco-inox-pedal-20l-soft-close",
    sku: "NX-LIX-001",
    short_description: "Lixeira 20L em inox escovado anti-marcas com fechamento suave da tampa.",
    description: "Higiene e sofisticação para sua cozinha. A Lixeira Nexlar 20L possui pedal robusto em aço e sistema Soft-Close que fecha a tampa suavemente sem fazer barulho.",
    category_id: "cat-lixeiras",
    categories: { name: "Lixeiras", slug: "lixeiras" },
    price: 189.90,
    compare_at_price: 249.90,
    pix_discount_percent: 10,
    stock: 40,
    rating: 4.8,
    reviews_count: 123,
    free_shipping: false,
    featured: true,
    is_new: false,
    active: true,
    created_at: "2026-09-08T10:00:00Z",
    highlights: ["Tampa Soft-Close anti-impacto", "Tratamento anti-digitais no inox", "Balde interno removível com alça", "Base antiderrapante"],
    specs: { "Capacidade": "20 Litros", "Material": "Aço Inox escovado AISI 430", "Dimensões": "29 x 45 cm", "Garantia": "3 anos" },
    product_images: [
      { id: "img-lix-01-1", url: "https://images.unsplash.com/photo-1585914924626-15adac1e6402?auto=format&fit=crop&w=1000&q=80", alt: "Lixeira em Aço Inox com Pedal Nexlar 20L", position: 0 },
      { id: "img-lix-01-2", url: "https://images.unsplash.com/photo-1613545325278-f24b0cae1224?auto=format&fit=crop&w=1000&q=80", alt: "Lixeira pedal detalhe balde interno", position: 1 },
    ],
  },
  {
    id: "prod-lix-02",
    name: "Lixeira Inteligente com Sensor Automático Nexlar 12L",
    slug: "lixeira-inteligente-sensor-automatico-12l",
    sku: "NX-LIX-002",
    short_description: "Abertura automática por aproximação sem contato físico. Higiene total.",
    description: "Com sensor infravermelho de resposta em 0.3s, a Lixeira Inteligente Nexlar abre ao aproximar a mão ou o joelho e fecha automaticamente após 5 segundos.",
    category_id: "cat-lixeiras",
    categories: { name: "Lixeiras", slug: "lixeiras" },
    price: 249.90,
    compare_at_price: 329.90,
    pix_discount_percent: 10,
    stock: 30,
    rating: 4.9,
    reviews_count: 89,
    free_shipping: false,
    featured: true,
    is_new: true,
    active: true,
    created_at: "2026-09-14T10:00:00Z",
    highlights: ["Sensor de movimento rápido e preciso", "Vedação anti-odor", "Bateria recarregável via USB-C ou pilhas", "Acabamento impermeável IPX5"],
    specs: { "Capacidade": "12 Litros", "Alimentação": "Bateria recarregável USB-C", "Material": "ABS premium e Inox", "Garantia": "1 ano" },
    product_images: [
      { id: "img-lix-02-1", url: "https://images.unsplash.com/photo-1613545325278-f24b0cae1224?auto=format&fit=crop&w=1000&q=80", alt: "Lixeira Inteligente com Sensor Nexlar", position: 0 },
      { id: "img-lix-02-2", url: "https://images.unsplash.com/photo-1585914924626-15adac1e6402?auto=format&fit=crop&w=1000&q=80", alt: "Lixeira com sensor aberta", position: 1 },
    ],
  },
  {
    id: "prod-lix-03",
    name: "Lixeira de Pia Basculante Nexlar Clean 5L",
    slug: "lixeira-pia-basculante-clean-5l",
    sku: "NX-LIX-003",
    short_description: "Lixeira compacta para bancada com tampa basculante e aro ocultador de saco.",
    description: "Mantenha a bancada da pia sempre limpa durante o preparo dos alimentos. Oculta totalmente o saco de lixo com seu anel interno.",
    category_id: "cat-lixeiras",
    categories: { name: "Lixeiras", slug: "lixeiras" },
    price: 69.90,
    compare_at_price: 89.90,
    pix_discount_percent: 10,
    stock: 80,
    rating: 4.6,
    reviews_count: 67,
    free_shipping: false,
    featured: false,
    is_new: false,
    active: true,
    created_at: "2026-09-04T10:00:00Z",
    highlights: ["Compacta para bancadas de cozinha ou banheiro", "Tampa basculante suave", "Esconde o saco plástico", "Fácil de lavar"],
    specs: { "Capacidade": "5 Litros", "Material": "Polipropileno virgem livre de BPA", "Cor": "Branco e Cinza Grafite", "Garantia": "1 ano" },
    product_images: [
      { id: "img-lix-03-1", url: "https://images.unsplash.com/photo-1585914924626-15adac1e6402?auto=format&fit=crop&w=1000&q=80", alt: "Lixeira de Pia Basculante Nexlar 5L", position: 0 },
      { id: "img-lix-03-2", url: "https://images.unsplash.com/photo-1613545325278-f24b0cae1224?auto=format&fit=crop&w=1000&q=80", alt: "Lixeira basculante sobre a bancada", position: 1 },
    ],
  },

  // ================= UTENSÍLIOS =================
  {
    id: "prod-utn-01",
    name: "Kit Utensílios de Cozinha em Silicone Nexlar Chef 8 Peças com Suporte",
    slug: "kit-utensilios-cozinha-silicone-chef-8pc-suporte",
    sku: "NX-UTN-001",
    short_description: "Silicone termorresistente até 230°C com cabos em madeira nobre e suporte de bancada.",
    description: "O jogo indispensável para proteger suas panelas antiaderentes contra riscos. Utensílios ergonômicos em silicone alimentício de alta densidade que não deformam e não absorvem cheiro.",
    category_id: "cat-utensilios",
    categories: { name: "Utensílios de Cozinha", slug: "utensilios-de-cozinha" },
    price: 159.90,
    compare_at_price: 209.90,
    pix_discount_percent: 10,
    stock: 45,
    rating: 4.9,
    reviews_count: 178,
    free_shipping: false,
    featured: true,
    is_new: false,
    active: true,
    created_at: "2026-09-10T10:00:00Z",
    highlights: ["Silicone 100% livre de BPA que resiste até 230°C", "Não risca panelas antiaderentes nem cerâmicas", "Cabos ergonômicos em madeira tratada", "Porta-utensílios de mesa incluso"],
    specs: { "Itens": "8 peças (espátula, concha, colher, pegador, escumadeira, fouet, pincel + porta-utensílios)", "Material": "Silicone alimentício e madeira", "Garantia": "1 ano" },
    product_images: [
      { id: "img-utn-01-1", url: "https://images.unsplash.com/photo-1565114616849-60c2f5ef9df7?auto=format&fit=crop&w=1000&q=80", alt: "Kit Utensílios de Silicone Nexlar Chef 8 Peças", position: 0 },
      { id: "img-utn-01-2", url: "https://images.unsplash.com/photo-1556909211-36987daf7b4d?auto=format&fit=crop&w=1000&q=80", alt: "Utensílios silicone detalhes", position: 1 },
    ],
  },
  {
    id: "prod-utn-02",
    name: "Tábua de Corte em Bambu Orgânico Nexlar Master 40x28cm",
    slug: "tabua-corte-bambu-organico-master-40x28",
    sku: "NX-UTN-002",
    short_description: "Bambu certificado naturalmente antibacteriano com canaleta coletora de sucos.",
    description: "Mais higiênica e resistente que a madeira comum. O bambu não retém umidade, não cega o fio das facas e possui canaleta profunda que impede líquidos de sujar a bancada.",
    category_id: "cat-utensilios",
    categories: { name: "Utensílios de Cozinha", slug: "utensilios-de-cozinha" },
    price: 79.90,
    compare_at_price: 99.90,
    pix_discount_percent: 10,
    stock: 65,
    rating: 4.8,
    reviews_count: 89,
    free_shipping: false,
    featured: false,
    is_new: false,
    active: true,
    created_at: "2026-09-07T10:00:00Z",
    highlights: ["Ação antibacteriana natural do bambu", "Canaleta lateral para reter líquidos", "Espessura de 1.8cm que não empena", "Fácil higienização"],
    specs: { "Dimensões": "40 x 28 x 1.8 cm", "Material": "100% Bambu natural ecológico", "Garantia": "1 ano" },
    product_images: [
      { id: "img-utn-02-1", url: "https://images.unsplash.com/photo-1556688517-7c27a4756dd0?auto=format&fit=crop&w=1000&q=80", alt: "Tábua de Corte em Bambu Nexlar Master", position: 0 },
      { id: "img-utn-02-2", url: "https://images.unsplash.com/photo-1575318634028-6a0cfcb60c59?auto=format&fit=crop&w=1000&q=80", alt: "Tábua de bambu com ingredientes", position: 1 },
    ],
  },
  {
    id: "prod-utn-03",
    name: "Escorredor de Louças em Aço Inox Nexlar Slim com Bandeja Coletora",
    slug: "escorredor-loucas-aco-inox-slim-bandeja",
    sku: "NX-UTN-003",
    short_description: "Escorredor inox com porta-talheres removível e calha direcionadora de água.",
    description: "Capacidade para 12 pratos, copos e talheres, direcionando a água diretamente para a cuba da pia sem molhar a bancada.",
    category_id: "cat-utensilios",
    categories: { name: "Utensílios de Cozinha", slug: "utensilios-de-cozinha" },
    price: 129.90,
    compare_at_price: 169.90,
    pix_discount_percent: 10,
    stock: 40,
    rating: 4.7,
    reviews_count: 76,
    free_shipping: false,
    featured: false,
    is_new: false,
    active: true,
    created_at: "2026-09-06T10:00:00Z",
    highlights: ["Aço inox que não enferruja", "Bandeja plástica com bico escoador 360°", "Porta-talheres com divisórias", "Pés emborrachados"],
    specs: { "Material": "Aço Inox e Polipropileno", "Dimensões": "42 x 30 x 14 cm", "Garantia": "3 anos" },
    product_images: [
      { id: "img-utn-03-1", url: "https://images.unsplash.com/photo-1556909211-36987daf7b4d?auto=format&fit=crop&w=1000&q=80", alt: "Escorredor de Louças Nexlar Inox Slim", position: 0 },
      { id: "img-utn-03-2", url: "https://images.unsplash.com/photo-1565114616849-60c2f5ef9df7?auto=format&fit=crop&w=1000&q=80", alt: "Escorredor inox sobre a bancada", position: 1 },
    ],
  },

  // ================= MESA & TALHERES =================
  {
    id: "prod-tal-01",
    name: "Faqueiro em Aço Inox Nexlar Bellagio 24 Peças em Estojo de Presente",
    slug: "faqueiro-aco-inox-bellagio-24pc-estojo",
    sku: "NX-TAL-001",
    short_description: "Serviço completo para 6 pessoas com acabamento espelhado e facas com têmpera especial.",
    description: "Linha premium de talheres em inox de alta densidade que não entortam. As facas possuem serrilha temperada que corta com extrema facilidade carnes e alimentos resistentes.",
    category_id: "cat-mesa",
    categories: { name: "Mesa & Talheres", slug: "mesa-e-talheres" },
    price: 199.90,
    compare_at_price: 259.90,
    pix_discount_percent: 10,
    stock: 35,
    rating: 4.9,
    reviews_count: 145,
    free_shipping: false,
    featured: true,
    is_new: false,
    active: true,
    created_at: "2026-09-09T10:00:00Z",
    highlights: ["24 peças para 6 pessoas", "Aço inox maciço de alta gramatura", "Pode ir à lava-louças diariamente", "Acompanha caixa litografada para presente"],
    specs: { "Conteúdo": "6 facas de mesa, 6 garfos de mesa, 6 colheres de mesa, 6 colheres de sobremesa", "Material": "Aço Inoxidável 18/0 e 18/10", "Garantia": "5 anos" },
    product_images: [
      { id: "img-tal-01-1", url: "https://images.unsplash.com/photo-1573821663912-569905455b1c?auto=format&fit=crop&w=1000&q=80", alt: "Faqueiro Inox Nexlar Bellagio 24 Peças", position: 0 },
      { id: "img-tal-01-2", url: "https://images.unsplash.com/photo-1579781354160-d9e12e4e2a8a?auto=format&fit=crop&w=1000&q=80", alt: "Talheres inox mesa posta", position: 1 },
    ],
  },
  {
    id: "prod-tal-02",
    name: "Faqueiro em Aço Inox Nexlar Gold Gourmet 42 Peças",
    slug: "faqueiro-aco-inox-gold-gourmet-42pc",
    sku: "NX-TAL-002",
    short_description: "Faqueiro completo para 8 pessoas incluindo concha, colher de servir e garfo trinchante.",
    description: "A composição perfeita para jantares com amigos e família. Peças com desenho clássico e balanceamento de peso impecável na mão.",
    category_id: "cat-mesa",
    categories: { name: "Mesa & Talheres", slug: "mesa-e-talheres" },
    price: 349.90,
    compare_at_price: 449.90,
    pix_discount_percent: 10,
    stock: 25,
    rating: 5.0,
    reviews_count: 89,
    free_shipping: true,
    featured: true,
    is_new: false,
    active: true,
    created_at: "2026-09-08T10:00:00Z",
    highlights: ["Atende até 8 pessoas com fartura", "Inclui peças mestras de serviço de travessa", "Brilho espelhado duradouro", "Design atemporal"],
    specs: { "Peças": "42 itens completos", "Material": "Aço Inox nobre", "Garantia": "10 anos" },
    product_images: [
      { id: "img-tal-02-1", url: "https://images.unsplash.com/photo-1579781354160-d9e12e4e2a8a?auto=format&fit=crop&w=1000&q=80", alt: "Faqueiro Nexlar Gold Gourmet 42 Peças", position: 0 },
      { id: "img-tal-02-2", url: "https://images.unsplash.com/photo-1573821663912-569905455b1c?auto=format&fit=crop&w=1000&q=80", alt: "Detalhe dos talheres", position: 1 },
    ],
  },
  {
    id: "prod-tal-03",
    name: "Bandeja de Servir em Aço Inox Nexlar Espelhada 40x25cm",
    slug: "bandeja-servir-aco-inox-espelhada-40x25",
    sku: "NX-TAL-003",
    short_description: "Bandeja retangular com alças integradas e bordas anti-queda.",
    description: "Ideal para servir café, drinks, aperitivos e pratos quentes direto à mesa com elegância e requinte.",
    category_id: "cat-mesa",
    categories: { name: "Mesa & Talheres", slug: "mesa-e-talheres" },
    price: 89.90,
    compare_at_price: 119.90,
    pix_discount_percent: 10,
    stock: 45,
    rating: 4.7,
    reviews_count: 45,
    free_shipping: false,
    featured: false,
    is_new: false,
    active: true,
    created_at: "2026-09-05T10:00:00Z",
    highlights: ["Acabamento inox espelhado", "Alças laterais anatômicas", "Bordas que evitam derramamentos", "Fácil de polir e limpar"],
    specs: { "Dimensões": "40 x 25 x 3 cm", "Material": "Aço Inox", "Garantia": "2 anos" },
    product_images: [
      { id: "img-tal-03-1", url: "https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?auto=format&fit=crop&w=1000&q=80", alt: "Bandeja de Servir Inox Nexlar Espelhada", position: 0 },
      { id: "img-tal-03-2", url: "https://images.unsplash.com/photo-1608835291093-394b0c943a75?auto=format&fit=crop&w=1000&q=80", alt: "Bandeja com taças e café", position: 1 },
    ],
  },

  // ================= ASSADEIRAS & FORMAS =================
  {
    id: "prod-ass-01",
    name: "Kit de Assadeiras Antiaderentes Nexlar Bakeware 3 Peças",
    slug: "kit-assadeiras-antiaderentes-bakeware-3pc",
    sku: "NX-ASS-001",
    short_description: "Conjunto com 3 assadeiras retangulares (pequena, média e grande) com antiaderente duplo.",
    description: "Asse bolos, carnes, frango assado e legumes sem grudar. O calor circula de maneira homogênea para assados dourados por fora e macios por dentro.",
    category_id: "cat-assadeiras",
    categories: { name: "Assadeiras & Formas", slug: "assadeiras-e-formas" },
    price: 149.90,
    compare_at_price: 199.90,
    pix_discount_percent: 10,
    stock: 40,
    rating: 4.8,
    reviews_count: 123,
    free_shipping: false,
    featured: true,
    is_new: false,
    active: true,
    created_at: "2026-09-09T10:00:00Z",
    highlights: ["3 tamanhos práticos que cabem em qualquer forno", "Revestimento antiaderente Pro de alta soltura", "Suporta temperaturas até 260°C", "Abas ergonômicas para pegar com luva"],
    specs: { "Dimensões": "P (28x18cm), M (33x23cm), G (38x27cm)", "Material": "Aço carbono com antiaderente", "Garantia": "2 anos" },
    product_images: [
      { id: "img-ass-01-1", url: "https://images.unsplash.com/photo-1555949258-eb67b1ef0ceb?auto=format&fit=crop&w=1000&q=80", alt: "Kit de Assadeiras Antiaderentes Nexlar 3 Peças", position: 0 },
      { id: "img-ass-01-2", url: "https://images.unsplash.com/photo-1614148644219-5d36f6f011fc?auto=format&fit=crop&w=1000&q=80", alt: "Assadeira com bolo recém assado", position: 1 },
    ],
  },
  {
    id: "prod-ass-02",
    name: "Forma de Bolo com Fundo Removível Nexlar 24cm",
    slug: "forma-bolo-fundo-removivel-24cm",
    sku: "NX-ASS-002",
    short_description: "Trava lateral springform e fundo texturizado para desenformar tortas e bolos perfeitos.",
    description: "O segredo para cheesecakes, tortas doces e bolos confeitados que saem intactos. A trava de liberação rápida abre a lateral sem tocar na massa.",
    category_id: "cat-assadeiras",
    categories: { name: "Assadeiras & Formas", slug: "assadeiras-e-formas" },
    price: 59.90,
    compare_at_price: 79.90,
    pix_discount_percent: 10,
    stock: 70,
    rating: 4.8,
    reviews_count: 78,
    free_shipping: false,
    featured: false,
    is_new: false,
    active: true,
    created_at: "2026-09-04T10:00:00Z",
    highlights: ["Sistema springform de abertura rápida", "Vedação anti-vazamento", "Antiaderente interno e externo", "Fundo texturizado antiaderente"],
    specs: { "Diâmetro": "24 cm", "Altura": "7 cm", "Material": "Aço carbono antiaderente", "Garantia": "1 ano" },
    product_images: [
      { id: "img-ass-02-1", url: "https://images.unsplash.com/photo-1555944956-30e4b9b8df5a?auto=format&fit=crop&w=1000&q=80", alt: "Forma de Bolo com Fundo Removível Nexlar", position: 0 },
      { id: "img-ass-02-2", url: "https://images.unsplash.com/photo-1555949258-eb67b1ef0ceb?auto=format&fit=crop&w=1000&q=80", alt: "Desenformando torta na forma", position: 1 },
    ],
  },

  // ================= ORGANIZAÇÃO =================
  {
    id: "prod-org-01",
    name: "Porta-Temperos Giratório em Inox Nexlar Spices 12 Frascos",
    slug: "porta-temperos-giratorio-inox-12-frascos",
    sku: "NX-ORG-001",
    short_description: "Base giratória 360° em inox com 12 potes de vidro herméticos e dosadores duplos.",
    description: "Tenha todos os condimentos e ervas ao alcance da mão durante o cozimento. Design elegante de bancada com tampas em inox e frascos de vidro grosso.",
    category_id: "cat-organizacao",
    categories: { name: "Organização", slug: "organizacao" },
    price: 119.90,
    compare_at_price: 159.90,
    pix_discount_percent: 10,
    stock: 45,
    rating: 4.9,
    reviews_count: 142,
    free_shipping: false,
    featured: true,
    is_new: false,
    active: true,
    created_at: "2026-09-11T10:00:00Z",
    highlights: ["Giro suave em 360 graus", "12 frascos de vidro transparente", "Tampas dosadoras com orifícios finos e grossos", "Aço inox escovado"],
    specs: { "Capacidade frascos": "100ml cada (12 unidades)", "Dimensões base": "18 x 22 cm", "Material": "Aço Inox e Vidro borossilicato", "Garantia": "2 anos" },
    product_images: [
      { id: "img-org-01-1", url: "https://images.unsplash.com/photo-1556228578-8c89e6adf883?auto=format&fit=crop&w=1000&q=80", alt: "Porta-Temperos Giratório Nexlar Inox 12 Frascos", position: 0 },
      { id: "img-org-01-2", url: "https://images.unsplash.com/photo-1493606278519-11aa9f86e40a?auto=format&fit=crop&w=1000&q=80", alt: "Frascos de condimentos organizados", position: 1 },
    ],
  },
  {
    id: "prod-org-02",
    name: "Conjunto de Potes Herméticos Nexlar ClearLock 10 Peças",
    slug: "conjunto-potes-hermeticos-clearlock-10pc",
    sku: "NX-ORG-002",
    short_description: "Acrílico crystal livre de BPA com travas 100% herméticas que conservam alimentos por mais tempo.",
    description: "Organize sua despensa e geladeira com máxima visibilidade e vedação a vácuo contra insetos e umidade. Empilhamento modular perfeito.",
    category_id: "cat-organizacao",
    categories: { name: "Organização", slug: "organizacao" },
    price: 199.90,
    compare_at_price: 259.90,
    pix_discount_percent: 10,
    stock: 35,
    rating: 4.9,
    reviews_count: 189,
    free_shipping: true,
    featured: true,
    is_new: true,
    active: true,
    created_at: "2026-09-15T10:00:00Z",
    highlights: ["Vedação com anel de silicone 100% hermético", "Acrílico ultra transparente de alta resistência", "Empilháveis para economizar espaço nos armários", "Livre de BPA"],
    specs: { "Volumes": "2x 1.9L, 2x 1.2L, 3x 800ml, 3x 500ml", "Material": "Acrílico San e anéis de silicone", "Garantia": "2 anos" },
    product_images: [
      { id: "img-org-02-1", url: "https://images.unsplash.com/photo-1493606278519-11aa9f86e40a?auto=format&fit=crop&w=1000&q=80", alt: "Conjunto de Potes Herméticos Nexlar ClearLock", position: 0 },
      { id: "img-org-02-2", url: "https://images.unsplash.com/photo-1556228578-8c89e6adf883?auto=format&fit=crop&w=1000&q=80", alt: "Despensa organizada com potes herméticos", position: 1 },
    ],
  },

  // ================= CHURRASCO =================
  {
    id: "prod-chr-01",
    name: "Kit Churrasco em Aço Inox Nexlar Fire Master 5 Peças com Maleta",
    slug: "kit-churrasco-inox-fire-master-5pc-maleta",
    sku: "NX-CHR-001",
    short_description: "Faca do chef, garfo trinchante, pegador longo, espátula multiúso e pincel em maleta de alumínio.",
    description: "O conjunto definitivo para mestres churrasqueiros. Ferramentas em aço inox de espessura reforçada com cabos ergonômicos resistentes ao calor da brasa.",
    category_id: "cat-churrasco",
    categories: { name: "Churrasco", slug: "churrasco" },
    price: 279.90,
    compare_at_price: 359.90,
    pix_discount_percent: 10,
    stock: 30,
    rating: 4.9,
    reviews_count: 89,
    free_shipping: true,
    featured: true,
    is_new: false,
    active: true,
    created_at: "2026-09-10T10:00:00Z",
    highlights: ["Aço inox maciço de alta resistência", "Comprimento extra para proteger do calor da brasa", "Maleta rígida de alumínio com travas", "Fio de faca com afiação duradoura"],
    specs: { "Itens": "Faca 8\", garfo, espátula vazada, pegador, pincel de silicone, maleta", "Material": "Aço Inox e Alumínio", "Garantia": "3 anos" },
    product_images: [
      { id: "img-chr-01-1", url: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=1000&q=80", alt: "Kit Churrasco Nexlar Fire Master com Maleta", position: 0 },
      { id: "img-chr-01-2", url: "https://images.unsplash.com/photo-1529692236671-f1f6cf9683ba?auto=format&fit=crop&w=1000&q=80", alt: "Utensílios de churrasco na brasa", position: 1 },
    ],
  },
  {
    id: "prod-chr-02",
    name: "Grelha Argentina em Aço Inox Nexlar 60x40cm com Calha Coletora",
    slug: "grelha-argentina-inox-60x40cm-calha",
    sku: "NX-CHR-002",
    short_description: "Canaletas em 'V' que recolhem a gordura evitando fumaça e labaredas na carne.",
    description: "A autêntica grelha argentina Parrilla: grelha as carnes suculentas sem queimá-las pelo fogo das gotas de gordura.",
    category_id: "cat-churrasco",
    categories: { name: "Churrasco", slug: "churrasco" },
    price: 349.90,
    compare_at_price: 449.90,
    pix_discount_percent: 10,
    stock: 20,
    rating: 4.8,
    reviews_count: 56,
    free_shipping: true,
    featured: false,
    is_new: false,
    active: true,
    created_at: "2026-09-08T10:00:00Z",
    highlights: ["Canaletas em V com leve inclinação", "Reservatório coletor de gordura removível", "Aço Inox 304 não enferruja", "Cabos em madeira pura"],
    specs: { "Área útil": "60 x 40 cm", "Material": "Aço Inox 304 espessura 1.5mm", "Garantia": "5 anos" },
    product_images: [
      { id: "img-chr-02-1", url: "https://images.unsplash.com/photo-1529692236671-f1f6cf9683ba?auto=format&fit=crop&w=1000&q=80", alt: "Grelha Argentina Inox Nexlar", position: 0 },
      { id: "img-chr-02-2", url: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=1000&q=80", alt: "Churrasco sendo preparado na grelha", position: 1 },
    ],
  },
];

// Funções de acesso rápido
export function getLocalCategories(): Category[] {
  return [...CATEGORIES].sort((a, b) => a.position - b.position);
}

export function getLocalCategoryBySlug(slug: string): Category | undefined {
  return CATEGORIES.find((c) => c.slug === slug);
}

export function getLocalBanners(): Banner[] {
  return [...BANNERS].sort((a, b) => a.position - b.position);
}

export function getLocalProducts(filter?: "featured" | "new" | "offers"): Product[] {
  let list = PRODUCTS.filter((p) => p.active);
  if (filter === "featured") list = list.filter((p) => p.featured);
  if (filter === "new") list = list.filter((p) => p.is_new);
  if (filter === "offers") list = list.filter((p) => p.compare_at_price && p.compare_at_price > p.price);
  return list;
}

export function getLocalProductsByCategory(categorySlugOrId: string): Product[] {
  const cat = CATEGORIES.find((c) => c.slug === categorySlugOrId || c.id === categorySlugOrId);
  if (!cat) return [];
  return PRODUCTS.filter((p) => p.category_id === cat.id || p.categories?.slug === cat.slug);
}

export function getLocalProductBySlug(slug: string): Product | undefined {
  return PRODUCTS.find((p) => p.slug === slug);
}

export function searchLocalProducts(term: string): Product[] {
  const q = term.toLowerCase().trim();
  if (!q) return [];
  return PRODUCTS.filter(
    (p) =>
      p.name.toLowerCase().includes(q) ||
      p.short_description?.toLowerCase().includes(q) ||
      p.categories?.name.toLowerCase().includes(q) ||
      p.highlights.some((h) => h.toLowerCase().includes(q)),
  );
}
