import type { Banner, Category, Product } from "./types";

export const CATEGORIES: Category[] = [
  {
    id: "cat-panelas",
    name: "Panelas",
    slug: "panelas",
    description: "Jogos de panelas antiaderentes, cerâmica e inox, frigideiras, caçarolas, woks e chaleiras.",
    image_url: "https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?auto=format&fit=crop&w=800&q=85",
    position: 1,
  },
  {
    id: "cat-pressao",
    name: "Panelas de Pressão",
    slug: "panelas-de-pressao",
    description: "Panelas de pressão com fechamento externo, interno e linha cerâmica antiaderente.",
    image_url: "https://images.unsplash.com/photo-1585515320310-259814833e62?auto=format&fit=crop&w=800&q=85",
    position: 2,
  },
  {
    id: "cat-eletro",
    name: "Eletroportáteis",
    slug: "eletroportateis",
    description: "Panelas de pressão elétricas digitais, fritadeiras e cooktops de indução portáteis.",
    image_url: "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=800&q=85",
    position: 3,
  },
  {
    id: "cat-lixeiras",
    name: "Lixeiras",
    slug: "lixeiras",
    description: "Lixeiras com pedal em inox, basculantes, com sensor de movimento e para coleta seletiva.",
    image_url: "https://images.unsplash.com/photo-1585914924626-15adac1e6402?auto=format&fit=crop&w=800&q=85",
    position: 4,
  },
  {
    id: "cat-utensilios",
    name: "Utensílios de Cozinha",
    slug: "utensilios-de-cozinha",
    description: "Kits de silicone alimentício, aço inox 18/10, tábuas de corte em bambu e escorredores.",
    image_url: "https://images.unsplash.com/photo-1565114616849-60c2f5ef9df7?auto=format&fit=crop&w=800&q=85",
    position: 5,
  },
  {
    id: "cat-mesa",
    name: "Mesa & Talheres",
    slug: "mesa-e-talheres",
    description: "Faqueiros completos em inox, bandejas de servir, bowls e porta-guardanapos.",
    image_url: "https://images.unsplash.com/photo-1573821663912-569905455b1c?auto=format&fit=crop&w=800&q=85",
    position: 6,
  },
  {
    id: "cat-assadeiras",
    name: "Assadeiras & Formas",
    slug: "assadeiras-e-formas",
    description: "Assadeiras antiaderentes, formas de bolo redondas, para lasanha e para pão.",
    image_url: "https://images.unsplash.com/photo-1555949258-eb67b1ef0ceb?auto=format&fit=crop&w=800&q=85",
    position: 7,
  },
  {
    id: "cat-organizacao",
    name: "Organização",
    slug: "organizacao",
    description: "Porta-temperos giratórios, potes herméticos em acrílico crystal e organizadores de pia.",
    image_url: "https://images.unsplash.com/photo-1493606278519-11aa9f86e40a?auto=format&fit=crop&w=800&q=85",
    position: 8,
  },
  {
    id: "cat-churrasco",
    name: "Churrasco",
    slug: "churrasco",
    description: "Kits de churrasco com maleta, grelhas argentinas em inox e churrasqueiras portáteis.",
    image_url: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=800&q=85",
    position: 9,
  },
];

export const BANNERS: Banner[] = [
  {
    id: "banner-1",
    title: "Antiaderente cerâmico que dura anos",
    subtitle: "Linha Ceramic Life Pro com fundo triplo, revestimento cerâmico livre de PFOA e compatibilidade total com indução.",
    eyebrow: "LINHA CERAMIC LIFE",
    cta_label: "Ver panelas",
    cta_url: "/categoria/panelas",
    image_url: "https://images.unsplash.com/photo-1556910103-1c02745aae4d?auto=format&fit=crop&w=1600&q=85",
    position: 1,
    active: true,
  },
  {
    id: "banner-2",
    title: "Pressão com segurança máxima",
    subtitle: "Panelas de pressão Nexlar com 5 sistemas de segurança certificados, aço inox e linha cerâmica antiaderente.",
    eyebrow: "PANELAS DE PRESSÃO",
    cta_label: "Ver panelas de pressão",
    cta_url: "/categoria/panelas-de-pressao",
    image_url: "https://images.unsplash.com/photo-1585515320310-259814833e62?auto=format&fit=crop&w=1600&q=85",
    position: 2,
    active: true,
  },
  {
    id: "banner-3",
    title: "Sua casa limpa e organizada",
    subtitle: "Porta-temperos giratórios, potes herméticos, lixeiras em aço inox com pedal e organizadores com design premium.",
    eyebrow: "ORGANIZAÇÃO & HIGIENE",
    cta_label: "Explorar organização",
    cta_url: "/categoria/organizacao",
    image_url: "https://images.unsplash.com/photo-1556228578-8c89e6adf883?auto=format&fit=crop&w=1600&q=85",
    position: 3,
    active: true,
  },
];

export const PRODUCTS: Product[] = [
  // ================= 1. PANELAS =================
  {
    id: "prod-pan-01",
    name: "Jogo de Panelas NEXLAR Ceramic Life Floria 10 Peças Rosa",
    slug: "jogo-de-panelas-nexlar-ceramic-life-floria-10-pecas-rosa",
    sku: "NX-7135200",
    short_description: "Conjunto completo 10 peças com revestimento cerâmico livre de PFOA, tampas de vidro temperado e cabos antitérmicos.",
    description: "O Jogo de Panelas NEXLAR Ceramic Life Floria 10 Peças Rosa une beleza, delicadeza e altíssima performance. Fabricado em alumínio reforçado com revestimento cerâmico Pro Ceramic, proporciona preparo saudável com menos óleo, não gruda e é facílimo de limpar. Acompanha tampas de vidro temperado com saída de vapor e utensílios em nylon.",
    category_id: "cat-panelas",
    categories: { name: "Panelas", slug: "panelas" },
    price: 399.99,
    compare_at_price: 699.99,
    pix_discount_percent: 10,
    stock: 45,
    rating: 4.9,
    reviews_count: 142,
    free_shipping: true,
    featured: true,
    is_new: true,
    active: true,
    created_at: "2026-09-18T10:00:00Z",
    highlights: ["Revestimento cerâmico Pro Ceramic sem PFOA", "10 peças completas para todas as receitas", "Tampas de vidro temperado com saída de vapor", "Cabos ergonômicos em baquelite antitérmico"],
    specs: { "Composição": "10 peças completas", "Estrutura": "Alumínio reforçado", "Revestimento": "Pro Ceramic", "Compatibilidade": "Gás, elétrico, vitrocerâmico", "Garantia": "12 meses" },
    product_images: [
      { id: "img-pan-01-1", url: "https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?auto=format&fit=crop&w=1000&q=85", alt: "Jogo de Panelas NEXLAR Ceramic Life Floria 10 Peças Rosa", position: 0 },
      { id: "img-pan-01-2", url: "https://images.unsplash.com/photo-1556910103-1c02745aae4d?auto=format&fit=crop&w=1000&q=85", alt: "Panelas Ceramic Life Floria na bancada", position: 1 },
    ],
  },
  {
    id: "prod-pan-02",
    name: "Jogo de Panelas NEXLAR Antiaderente Ceramic Life 8 Peças Smart Plus Vanilla",
    slug: "jogo-de-panelas-nexlar-ceramic-life-8-pecas-smart-plus-vanilla",
    sku: "NX-7128100",
    short_description: "Conjunto 8 peças em cerâmica antiaderente na cor vanilla com tampas de vidro e cabos soft-touch.",
    description: "Sofisticação e tecnologia para sua cozinha. O Jogo de Panelas NEXLAR Smart Plus Vanilla conta com estrutura em alumínio de alta densidade que aquece rápido e distribui o calor por igual, reduzindo o tempo de preparo.",
    category_id: "cat-panelas",
    categories: { name: "Panelas", slug: "panelas" },
    price: 489.90,
    compare_at_price: 649.90,
    pix_discount_percent: 10,
    stock: 35,
    rating: 4.9,
    reviews_count: 215,
    free_shipping: true,
    featured: true,
    is_new: false,
    active: true,
    created_at: "2026-09-17T10:00:00Z",
    highlights: ["8 peças incluindo caçarolas, panelas, frigideiras e fervedor", "Antiaderente cerâmico Mineral Resist", "Tampas de vidro temperado", "Cabos com toque aveludado soft-touch"],
    specs: { "Peças": "8 peças", "Cor": "Vanilla / Off-white", "Material": "Alumínio 3.0mm com cerâmica", "Garantia": "12 meses" },
    product_images: [
      { id: "img-pan-02-1", url: "https://images.unsplash.com/photo-1590794056226-79ef3a8147e1?auto=format&fit=crop&w=1000&q=85", alt: "Jogo de Panelas NEXLAR Smart Plus Vanilla 8 Peças", position: 0 },
      { id: "img-pan-02-2", url: "https://images.unsplash.com/photo-1556910103-1c02745aae4d?auto=format&fit=crop&w=1000&q=85", alt: "Conjunto Smart Plus na bancada", position: 1 },
    ],
  },
  {
    id: "prod-pan-03",
    name: "Jogo de Panelas Inox NEXLAR Supreme 7 Peças com Fundo Triplo",
    slug: "jogo-de-panelas-inox-nexlar-supreme-7-pecas-fundo-triplo",
    sku: "NX-4828111",
    short_description: "Aço inoxidável 18/10 com fundo triplo encapsulado compatível com fogão de indução.",
    description: "Design clássico e durabilidade para toda a vida. O aço inox nobre da linha NEXLAR Supreme não libera resíduos nos alimentos, não mancha e pode ir à lava-louças todos os dias.",
    category_id: "cat-panelas",
    categories: { name: "Panelas", slug: "panelas" },
    price: 549.90,
    compare_at_price: 799.90,
    pix_discount_percent: 10,
    stock: 30,
    rating: 5.0,
    reviews_count: 178,
    free_shipping: true,
    featured: true,
    is_new: false,
    active: true,
    created_at: "2026-09-16T10:00:00Z",
    highlights: ["Aço Inox 18/10 cirúrgico espelhado", "Fundo triplo (Inox + Alumínio + Inox)", "100% compatível com indução", "Garantia estendida oficial NEXLAR"],
    specs: { "Peças": "7 peças completas", "Material": "Aço Inoxidável 18/10", "Garantia": "5 anos" },
    product_images: [
      { id: "img-pan-03-1", url: "https://images.unsplash.com/photo-1585515320310-259814833e62?auto=format&fit=crop&w=1000&q=85", alt: "Jogo de Panelas Inox NEXLAR Supreme 7 Peças", position: 0 },
      { id: "img-pan-03-2", url: "https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=1000&q=85", alt: "Panelas inox acabamento espelhado", position: 1 },
    ],
  },
  {
    id: "prod-pan-04",
    name: "Frigideira Antiaderente NEXLAR Ceramic Life 24cm",
    slug: "frigideira-antiaderente-nexlar-ceramic-life-24cm",
    sku: "NX-7001240",
    short_description: "Frigideira 24cm em cerâmica antiaderente livre de PFOA com cabo antitérmico.",
    description: "Perfeita para o dia a dia: grelhe carnes, frangos, peixes, tapiocas e ovos com uma gota de óleo ou sem óleo. O revestimento cerâmico de alta densidade não descasca.",
    category_id: "cat-panelas",
    categories: { name: "Panelas", slug: "panelas" },
    price: 139.90,
    compare_at_price: 189.90,
    pix_discount_percent: 10,
    stock: 60,
    rating: 4.8,
    reviews_count: 164,
    free_shipping: false,
    featured: false,
    is_new: false,
    active: true,
    created_at: "2026-09-15T10:00:00Z",
    highlights: ["Diâmetro de 24cm com borda alta anti-respingo", "Revestimento cerâmico ultra resistente", "Cabo soft-touch anatômico", "Fácil lavagem"],
    specs: { "Diâmetro": "24 cm", "Capacidade": "1.45 Litros", "Material": "Alumínio 3.0mm com cerâmica", "Garantia": "12 meses" },
    product_images: [
      { id: "img-pan-04-1", url: "https://images.unsplash.com/photo-1534361960057-19f4434a4d4e?auto=format&fit=crop&w=1000&q=85", alt: "Frigideira Antiaderente NEXLAR Ceramic Life 24cm", position: 0 },
      { id: "img-pan-04-2", url: "https://images.unsplash.com/photo-1571167366136-b57e5ee84b27?auto=format&fit=crop&w=1000&q=85", alt: "Frigideira em preparo de receita", position: 1 },
    ],
  },
  {
    id: "prod-pan-05",
    name: "Wok Antiaderente NEXLAR Asian Gourmet 32cm com Tampa de Vidro",
    slug: "wok-antiaderente-nexlar-asian-gourmet-32cm-tampa",
    sku: "NX-7001320",
    short_description: "Wok oriental 32cm profundo ideal para saltear legumes, carnes e yakisoba.",
    description: "Prepare pratos asiáticos e salteados perfeitos. Seu formato arredondado permite movimentar os ingredientes rapidamente sob calor intenso, mantendo o sabor e nutrientes.",
    category_id: "cat-panelas",
    categories: { name: "Panelas", slug: "panelas" },
    price: 199.90,
    compare_at_price: 269.90,
    pix_discount_percent: 10,
    stock: 40,
    rating: 4.9,
    reviews_count: 98,
    free_shipping: false,
    featured: false,
    is_new: false,
    active: true,
    created_at: "2026-09-14T10:00:00Z",
    highlights: ["Amplo diâmetro de 32cm", "Tampa de vidro com respiro de vapor", "Cabo longo reforçado", "Antiaderente cerâmico de alta performance"],
    specs: { "Diâmetro": "32 cm", "Capacidade": "4.8 Litros", "Material": "Alumínio com revestimento cerâmico", "Garantia": "12 meses" },
    product_images: [
      { id: "img-pan-05-1", url: "https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&w=1000&q=85", alt: "Wok Antiaderente NEXLAR Asian Gourmet 32cm", position: 0 },
      { id: "img-pan-05-2", url: "https://images.unsplash.com/photo-1586190848861-99aa4a171e90?auto=format&fit=crop&w=1000&q=85", alt: "Wok em uso", position: 1 },
    ],
  },
  {
    id: "prod-pan-06",
    name: "Chaleira em Aço Inox NEXLAR com Apito 2.2L",
    slug: "chaleira-aco-inox-nexlar-com-apito-2-2l",
    sku: "NX-4800220",
    short_description: "Chaleira clássica com apito sonoro de fervura, gatilho no cabo e fundo triplo.",
    description: "Segurança e charme ao ferver água para chá ou café. Possui apito harmônico que avisa quando a água atinge a temperatura ideal.",
    category_id: "cat-panelas",
    categories: { name: "Panelas", slug: "panelas" },
    price: 129.90,
    compare_at_price: 169.90,
    pix_discount_percent: 10,
    stock: 50,
    rating: 4.8,
    reviews_count: 112,
    free_shipping: false,
    featured: false,
    is_new: false,
    active: true,
    created_at: "2026-09-13T10:00:00Z",
    highlights: ["Apito sonoro ao atingir fervura", "Aço inox escovado durável", "Gatilho de abertura segura no cabo", "Compatível com todos os fogões"],
    specs: { "Capacidade": "2.2 Litros", "Material": "Aço Inoxidável", "Garantia": "12 meses" },
    product_images: [
      { id: "img-pan-06-1", url: "https://images.unsplash.com/photo-1510774463633-28c33ef2c16d?auto=format&fit=crop&w=1000&q=85", alt: "Chaleira em Aço Inox NEXLAR com Apito", position: 0 },
      { id: "img-pan-06-2", url: "https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=1000&q=85", alt: "Chaleira inox sobre o fogão", position: 1 },
    ],
  },

  // ================= 2. PANELAS DE PRESSÃO =================
  {
    id: "prod-pre-01",
    name: "Panela de Pressão Inox NEXLAR Security 4.5L Fechamento Externo",
    slug: "panela-de-pressao-inox-nexlar-security-4-5l-fechamento-externo",
    sku: "NX-6001450",
    short_description: "Panela de pressão em inox 18/10 com 5 sistemas independentes de segurança e fundo triplo.",
    description: "Cozinhe feijão, carnes e sopas na metade do tempo com total segurança e tranquilidade. A Panela de Pressão NEXLAR Security possui tampa de fechamento externo de encaixe rápido e corpo em aço inox 18/10.",
    category_id: "cat-pressao",
    categories: { name: "Panelas de Pressão", slug: "panelas-de-pressao" },
    price: 269.90,
    compare_at_price: 359.90,
    pix_discount_percent: 10,
    stock: 45,
    rating: 4.9,
    reviews_count: 198,
    free_shipping: true,
    featured: true,
    is_new: false,
    active: true,
    created_at: "2026-09-17T10:00:00Z",
    highlights: ["5 dispositivos de segurança certificados", "Fechamento externo ergonômico", "Fundo triplo compatível com indução", "Aço inox de alta espessura"],
    specs: { "Capacidade": "4.5 Litros", "Material": "Aço Inox 18/10", "Pressão": "80 kPa", "Garantia": "5 anos" },
    product_images: [
      { id: "img-pre-01-1", url: "https://images.unsplash.com/photo-1595587637401-83ff822bd63b?auto=format&fit=crop&w=1000&q=85", alt: "Panela de Pressão Inox NEXLAR Security 4.5L", position: 0 },
      { id: "img-pre-01-2", url: "https://images.unsplash.com/photo-1585515320310-259814833e62?auto=format&fit=crop&w=1000&q=85", alt: "Válvulas de segurança panela de pressão", position: 1 },
    ],
  },
  {
    id: "prod-pre-02",
    name: "Panela de Pressão Cerâmica NEXLAR Pressure 4.2L Antiaderente Vanilla",
    slug: "panela-de-pressao-ceramica-nexlar-pressure-4-2l-antiaderente-vanilla",
    sku: "NX-6002420",
    short_description: "Revestimento cerâmico interno antiaderente que não queima alimentos no fundo.",
    description: "A inovação que une o poder da pressão com a facilidade da cerâmica antiaderente. Não gruda, cozinha mais rápido e limpa em segundos.",
    category_id: "cat-pressao",
    categories: { name: "Panelas de Pressão", slug: "panelas-de-pressao" },
    price: 339.90,
    compare_at_price: 439.90,
    pix_discount_percent: 10,
    stock: 35,
    rating: 4.9,
    reviews_count: 145,
    free_shipping: true,
    featured: true,
    is_new: true,
    active: true,
    created_at: "2026-09-16T10:00:00Z",
    highlights: ["Interior com cerâmica antiaderente livre de PFOA", "Não deixa o feijão grudar no fundo", "Fechamento externo ultra seguro", "Compatível com fogões a gás e indução"],
    specs: { "Capacidade": "4.2 Litros", "Cor": "Vanilla / Areia", "Material": "Alumínio forjado com cerâmica", "Garantia": "2 anos" },
    product_images: [
      { id: "img-pre-02-1", url: "https://images.unsplash.com/photo-1556910103-1c02745aae4d?auto=format&fit=crop&w=1000&q=85", alt: "Panela de Pressão Cerâmica NEXLAR Pressure 4.2L", position: 0 },
      { id: "img-pre-02-2", url: "https://images.unsplash.com/photo-1595587637401-83ff822bd63b?auto=format&fit=crop&w=1000&q=85", alt: "Tampa de fechamento cerâmica", position: 1 },
    ],
  },
  {
    id: "prod-pre-03",
    name: "Panela de Pressão NEXLAR Tradicional 4.5L Fechamento Interno",
    slug: "panela-de-pressao-nexlar-tradicional-4-5l-fechamento-interno",
    sku: "NX-6003450",
    short_description: "Modelo clássico de alta resistência em alumínio polido com válvula de segurança em silicone.",
    description: "A clássica e confiável panela de pressão com vedação reforçada e haste de aço com pega ergonômica.",
    category_id: "cat-pressao",
    categories: { name: "Panelas de Pressão", slug: "panelas-de-pressao" },
    price: 179.90,
    compare_at_price: 229.90,
    pix_discount_percent: 10,
    stock: 50,
    rating: 4.7,
    reviews_count: 132,
    free_shipping: false,
    featured: false,
    is_new: false,
    active: true,
    created_at: "2026-09-12T10:00:00Z",
    highlights: ["Vedação hermética em silicone", "Alumínio polido de espessura grossa", "Cabo anatômico antiaquecimento", "Válvula de controle contínuo"],
    specs: { "Capacidade": "4.5 Litros", "Material": "Alumínio reforçado", "Garantia": "2 anos" },
    product_images: [
      { id: "img-pre-03-1", url: "https://images.unsplash.com/photo-1595587637401-83ff822bd63b?auto=format&fit=crop&w=1000&q=85", alt: "Panela de Pressão NEXLAR Tradicional 4.5L", position: 0 },
      { id: "img-pre-03-2", url: "https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=1000&q=85", alt: "Panela de pressão fechamento interno", position: 1 },
    ],
  },

  // ================= 3. ELETROPORTÁTEIS =================
  {
    id: "prod-ele-01",
    name: "Panela de Pressão Elétrica Digital NEXLAR Smart Chef 6L 1000W",
    slug: "panela-de-pressao-eletrica-digital-nexlar-smart-chef-6l-1000w",
    sku: "NX-8001100",
    short_description: "12 funções automáticas na tela touch, timer de até 24h, cuba antiaderente e desligamento automático.",
    description: "Praticidade absoluta para seu dia a dia. Basta colocar os ingredientes, selecionar a receita no painel touch digital e deixar que a Panela de Pressão Elétrica NEXLAR cozinhe tudo com precisão, silêncio e segurança, mantendo os alimentos aquecidos após o término.",
    category_id: "cat-eletro",
    categories: { name: "Eletroportáteis", slug: "eletroportateis" },
    price: 499.99,
    compare_at_price: 624.99,
    pix_discount_percent: 10,
    stock: 30,
    rating: 4.9,
    reviews_count: 201,
    free_shipping: true,
    featured: true,
    is_new: true,
    active: true,
    created_at: "2026-09-18T10:00:00Z",
    highlights: ["Painel touch digital com 12 programas pré-definidos", "Capacidade generosa de 6 Litros", "Cuba interna antiaderente removível de fácil lavagem", "Totalmente silenciosa e sem vapor constante"],
    specs: { "Capacidade": "6.0 Litros", "Potência": "1000W", "Voltagem": "110V / 220V", "Garantia": "12 meses" },
    product_images: [
      { id: "img-ele-01-1", url: "https://images.unsplash.com/photo-1556909212-d5b604d0c90d?auto=format&fit=crop&w=1000&q=85", alt: "Panela de Pressão Elétrica Digital NEXLAR Smart Chef 6L", position: 0 },
      { id: "img-ele-01-2", url: "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=1000&q=85", alt: "Painel digital touch panela elétrica", position: 1 },
    ],
  },
  {
    id: "prod-ele-02",
    name: "Cooktop Portátil de Indução NEXLAR Slim Touch 2200W",
    slug: "cooktop-portatil-de-inducao-nexlar-slim-touch-2200w",
    sku: "NX-8002200",
    short_description: "Cooktop de indução ultra fino com mesa vitrocerâmica, 9 níveis de temperatura e trava de segurança infantil.",
    description: "Cozinhe com eficiência e rapidez em qualquer lugar. O Cooktop de Indução NEXLAR ferve água na metade do tempo do fogão a gás e esfria instantaneamente ao remover a panela.",
    category_id: "cat-eletro",
    categories: { name: "Eletroportáteis", slug: "eletroportateis" },
    price: 299.90,
    compare_at_price: 399.90,
    pix_discount_percent: 10,
    stock: 40,
    rating: 4.8,
    reviews_count: 145,
    free_shipping: true,
    featured: true,
    is_new: false,
    active: true,
    created_at: "2026-09-15T10:00:00Z",
    highlights: ["2200W de potência instantânea", "Mesa vitrocerâmica lisa de fácil limpeza", "Timer digital programável até 180 min", "Reconhecimento automático de panelas"],
    specs: { "Potência": "2200W", "Temperatura": "60°C a 240°C", "Dimensões": "28 x 35 x 4.5 cm", "Garantia": "12 meses" },
    product_images: [
      { id: "img-ele-02-1", url: "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=1000&q=85", alt: "Cooktop Portátil de Indução NEXLAR Slim Touch", position: 0 },
      { id: "img-ele-02-2", url: "https://images.unsplash.com/photo-1556909212-d5b604d0c90d?auto=format&fit=crop&w=1000&q=85", alt: "Cooktop indução sobre a bancada", position: 1 },
    ],
  },

  // ================= 4. LIXEIRAS =================
  {
    id: "prod-lix-01",
    name: "Lixeira em Aço Inox com Pedal NEXLAR Spin 20L Escovada Soft-Close",
    slug: "lixeira-em-aco-inox-com-pedal-nexlar-spin-20l-escovada-soft-close",
    sku: "NX-3069200",
    short_description: "Lixeira 20L em aço inox escovado anti-marcas com pedal reforçado e fechamento suave da tampa.",
    description: "Higiene, resistência e sofisticação para sua cozinha. A Lixeira NEXLAR Spin 20L possui tratamento anti-digitais no aço inox, balde interno removível com alça e sistema de fechamento suave sem barulho.",
    category_id: "cat-lixeiras",
    categories: { name: "Lixeiras", slug: "lixeiras" },
    price: 189.99,
    compare_at_price: 249.99,
    pix_discount_percent: 10,
    stock: 40,
    rating: 4.8,
    reviews_count: 175,
    free_shipping: false,
    featured: true,
    is_new: false,
    active: true,
    created_at: "2026-09-17T10:00:00Z",
    highlights: ["Tampa Soft-Close com amortecedor silencioso", "Aço Inox escovado com película anti-marcas", "Balde interno removível com alça metálica", "Base emborrachada antiderrapante"],
    specs: { "Capacidade": "20 Litros", "Material": "Aço Inox escovado e ABS", "Dimensões": "28 x 45 cm", "Garantia": "3 anos" },
    product_images: [
      { id: "img-lix-01-1", url: "https://images.unsplash.com/photo-1585914924626-15adac1e6402?auto=format&fit=crop&w=1000&q=85", alt: "Lixeira em Aço Inox com Pedal NEXLAR Spin 20L", position: 0 },
      { id: "img-lix-01-2", url: "https://images.unsplash.com/photo-1613545325278-f24b0cae1224?auto=format&fit=crop&w=1000&q=85", alt: "Lixeira pedal detalhe balde interno", position: 1 },
    ],
  },
  {
    id: "prod-lix-02",
    name: "Lixeira Inteligente com Sensor Automático NEXLAR SensorClean 12L",
    slug: "lixeira-inteligente-com-sensor-automatico-nexlar-sensorclean-12l",
    sku: "NX-3069120",
    short_description: "Abertura automática por sensor infravermelho sem toque. Higiene máxima para sua casa.",
    description: "Abra e feche sem encostar as mãos. O sensor rápido detecta aproximação a até 25cm e fecha automaticamente após 5 segundos, garantindo contenção de odores e limpeza impecável.",
    category_id: "cat-lixeiras",
    categories: { name: "Lixeiras", slug: "lixeiras" },
    price: 249.90,
    compare_at_price: 329.90,
    pix_discount_percent: 10,
    stock: 35,
    rating: 4.9,
    reviews_count: 114,
    free_shipping: false,
    featured: true,
    is_new: true,
    active: true,
    created_at: "2026-09-18T10:00:00Z",
    highlights: ["Abertura por sensor infravermelho de 0.3s", "Vedação anti-odor hermética", "Bateria recarregável via USB-C de longa duração", "Design minimalista premium"],
    specs: { "Capacidade": "12 Litros", "Alimentação": "Bateria recarregável USB-C", "Material": "ABS premium e Inox", "Garantia": "12 meses" },
    product_images: [
      { id: "img-lix-02-1", url: "https://images.unsplash.com/photo-1613545325278-f24b0cae1224?auto=format&fit=crop&w=1000&q=85", alt: "Lixeira Inteligente com Sensor Automático NEXLAR 12L", position: 0 },
      { id: "img-lix-02-2", url: "https://images.unsplash.com/photo-1585914924626-15adac1e6402?auto=format&fit=crop&w=1000&q=85", alt: "Lixeira inteligente aberta", position: 1 },
    ],
  },
  {
    id: "prod-lix-03",
    name: "Lixeira de Pia Basculante NEXLAR Clean 5L Branco",
    slug: "lixeira-de-pia-basculante-nexlar-clean-5l-branco",
    sku: "NX-3069050",
    short_description: "Lixeira compacta de bancada com tampa basculante que esconde totalmente o saco de lixo.",
    description: "Desenvolvida para deixar a bancada da cozinha limpa e organizada durante o preparo dos alimentos. O anel interno prende e oculta o saco plástico.",
    category_id: "cat-lixeiras",
    categories: { name: "Lixeiras", slug: "lixeiras" },
    price: 69.90,
    compare_at_price: 89.90,
    pix_discount_percent: 10,
    stock: 80,
    rating: 4.7,
    reviews_count: 88,
    free_shipping: false,
    featured: false,
    is_new: false,
    active: true,
    created_at: "2026-09-11T10:00:00Z",
    highlights: ["Tampa basculante com giro suave", "Anel ocultador de saco plástico", "Material 100% livre de BPA", "Ideal para cozinha ou banheiro"],
    specs: { "Capacidade": "5 Litros", "Cor": "Branco / Matte", "Dimensões": "20 x 24 cm", "Garantia": "12 meses" },
    product_images: [
      { id: "img-lix-03-1", url: "https://images.unsplash.com/photo-1585914924626-15adac1e6402?auto=format&fit=crop&w=1000&q=85", alt: "Lixeira de Pia Basculante NEXLAR Clean 5L", position: 0 },
      { id: "img-lix-03-2", url: "https://images.unsplash.com/photo-1613545325278-f24b0cae1224?auto=format&fit=crop&w=1000&q=85", alt: "Lixeira basculante sobre a bancada", position: 1 },
    ],
  },

  // ================= 5. UTENSÍLIOS DE COZINHA =================
  {
    id: "prod-utn-01",
    name: "Kit Utensílios de Cozinha em Silicone NEXLAR Chef 8 Peças com Suporte",
    slug: "kit-utensilios-de-cozinha-em-silicone-nexlar-chef-8-pecas-suporte",
    sku: "NX-2001080",
    short_description: "Silicone termorresistente até 230°C com cabos em madeira nobre tratada e porta-utensílios.",
    description: "O conjunto que não risca suas panelas antiaderentes e cerâmicas. Fabricado em silicone alimentício virgem livre de BPA que não absorve odores nem mancha.",
    category_id: "cat-utensilios",
    categories: { name: "Utensílios de Cozinha", slug: "utensilios-de-cozinha" },
    price: 159.90,
    compare_at_price: 219.90,
    pix_discount_percent: 10,
    stock: 50,
    rating: 4.9,
    reviews_count: 165,
    free_shipping: false,
    featured: true,
    is_new: false,
    active: true,
    created_at: "2026-09-16T10:00:00Z",
    highlights: ["Silicone de grau alimentício livre de BPA", "Resistente a temperaturas de até 230°C", "Não risca panelas cerâmicas", "Porta-utensílios incluso"],
    specs: { "Itens": "8 peças (espátula, concha, colher, pegador, escumadeira, fouet, pincel + suporte)", "Material": "Silicone e Madeira nobre", "Garantia": "12 meses" },
    product_images: [
      { id: "img-utn-01-1", url: "https://images.unsplash.com/photo-1565114616849-60c2f5ef9df7?auto=format&fit=crop&w=1000&q=85", alt: "Kit Utensílios de Cozinha em Silicone NEXLAR Chef 8 Peças", position: 0 },
      { id: "img-utn-01-2", url: "https://images.unsplash.com/photo-1556909211-36987daf7b4d?auto=format&fit=crop&w=1000&q=85", alt: "Utensílios de silicone detalhes", position: 1 },
    ],
  },
  {
    id: "prod-utn-02",
    name: "Tábua de Corte em Bambu Orgânico NEXLAR Master 40x28cm",
    slug: "tabua-de-corte-em-bambu-organico-nexlar-master-40x28cm",
    sku: "NX-2002400",
    short_description: "Bambu certificado naturalmente antibacteriano com canaleta coletora de sucos e alta espessura.",
    description: "Muito mais higiênica e resistente. O bambu ecológico não desgasta o fio das facas e sua canaleta profunda impede o derramamento de líquidos na bancada.",
    category_id: "cat-utensilios",
    categories: { name: "Utensílios de Cozinha", slug: "utensilios-de-cozinha" },
    price: 79.90,
    compare_at_price: 99.90,
    pix_discount_percent: 10,
    stock: 65,
    rating: 4.8,
    reviews_count: 94,
    free_shipping: false,
    featured: false,
    is_new: false,
    active: true,
    created_at: "2026-09-14T10:00:00Z",
    highlights: ["Ação antibacteriana natural do bambu", "Canaleta coletora de líquidos", "Espessura de 1.8cm que não empena", "Fácil higienização"],
    specs: { "Dimensões": "40 x 28 x 1.8 cm", "Material": "100% Bambu ecológico", "Garantia": "12 meses" },
    product_images: [
      { id: "img-utn-02-1", url: "https://images.unsplash.com/photo-1556688517-7c27a4756dd0?auto=format&fit=crop&w=1000&q=85", alt: "Tábua de Corte em Bambu NEXLAR Master", position: 0 },
      { id: "img-utn-02-2", url: "https://images.unsplash.com/photo-1575318634028-6a0cfcb60c59?auto=format&fit=crop&w=1000&q=85", alt: "Tábua de bambu com alimentos", position: 1 },
    ],
  },
  {
    id: "prod-utn-03",
    name: "Escorredor de Louças em Aço Inox NEXLAR Slim com Calha 360°",
    slug: "escorredor-de-loucas-em-aco-inox-nexlar-slim-calha-360",
    sku: "NX-2003420",
    short_description: "Aço inox escovado com bandeja drenadora que escoa a água direto para a cuba da pia.",
    description: "Capacidade para pratos, copos e talheres, eliminando o acúmulo de água na bancada com seu bico direcionador giratório.",
    category_id: "cat-utensilios",
    categories: { name: "Utensílios de Cozinha", slug: "utensilios-de-cozinha" },
    price: 139.90,
    compare_at_price: 179.90,
    pix_discount_percent: 10,
    stock: 45,
    rating: 4.8,
    reviews_count: 82,
    free_shipping: false,
    featured: false,
    is_new: false,
    active: true,
    created_at: "2026-09-13T10:00:00Z",
    highlights: ["Aço Inox que não enferruja", "Bandeja coletora com bico giratório 360°", "Porta-talheres removível", "Pés antiderrapantes"],
    specs: { "Material": "Aço Inox e Polipropileno", "Dimensões": "42 x 30 x 14 cm", "Garantia": "3 anos" },
    product_images: [
      { id: "img-utn-03-1", url: "https://images.unsplash.com/photo-1556909211-36987daf7b4d?auto=format&fit=crop&w=1000&q=85", alt: "Escorredor de Louças em Aço Inox NEXLAR Slim", position: 0 },
      { id: "img-utn-03-2", url: "https://images.unsplash.com/photo-1565114616849-60c2f5ef9df7?auto=format&fit=crop&w=1000&q=85", alt: "Escorredor inox sobre a bancada", position: 1 },
    ],
  },

  // ================= 6. MESA & TALHERES =================
  {
    id: "prod-tal-01",
    name: "Faqueiro em Aço Inox NEXLAR Bellagio 24 Peças em Estojo de Presente",
    slug: "faqueiro-em-aco-inox-nexlar-bellagio-24-pecas-estojo-presente",
    sku: "NX-5001240",
    short_description: "Faqueiro para 6 pessoas em aço inox nobre com brilho espelhado e facas com têmpera especial.",
    description: "Elegância e alta gramatura para compor sua mesa posta. As peças contam com polimento espelhado premium e facas afiadas que não perdem o corte.",
    category_id: "cat-mesa",
    categories: { name: "Mesa & Talheres", slug: "mesa-e-talheres" },
    price: 199.90,
    compare_at_price: 269.90,
    pix_discount_percent: 10,
    stock: 40,
    rating: 4.9,
    reviews_count: 153,
    free_shipping: false,
    featured: true,
    is_new: false,
    active: true,
    created_at: "2026-09-17T10:00:00Z",
    highlights: ["24 peças completas para 6 pessoas", "Aço Inox maciço de alta durabilidade", "Pode ir à lava-louças", "Estojo rígido para presente"],
    specs: { "Composição": "6 garfos, 6 facas, 6 colheres de sopa, 6 colheres de sobremesa", "Material": "Aço Inox 18/10", "Garantia": "5 anos" },
    product_images: [
      { id: "img-tal-01-1", url: "https://images.unsplash.com/photo-1573821663912-569905455b1c?auto=format&fit=crop&w=1000&q=85", alt: "Faqueiro em Aço Inox NEXLAR Bellagio 24 Peças", position: 0 },
      { id: "img-tal-01-2", url: "https://images.unsplash.com/photo-1579781354160-d9e12e4e2a8a?auto=format&fit=crop&w=1000&q=85", alt: "Talheres inox mesa posta", position: 1 },
    ],
  },
  {
    id: "prod-tal-02",
    name: "Faqueiro em Aço Inox NEXLAR Gourmet 42 Peças",
    slug: "faqueiro-em-aco-inox-nexlar-gourmet-42-pecas",
    sku: "NX-5001420",
    short_description: "Serviço completo para 8 pessoas incluindo concha de terrina, colheres de servir e garfo trinchante.",
    description: "O faqueiro ideal para almoços e jantares memoráveis com a família. Acabamento clássico, peso equilibrado e corte impecável.",
    category_id: "cat-mesa",
    categories: { name: "Mesa & Talheres", slug: "mesa-e-talheres" },
    price: 349.90,
    compare_at_price: 459.90,
    pix_discount_percent: 10,
    stock: 25,
    rating: 5.0,
    reviews_count: 98,
    free_shipping: true,
    featured: true,
    is_new: false,
    active: true,
    created_at: "2026-09-15T10:00:00Z",
    highlights: ["Atende 8 pessoas com conjunto mestre de servir", "Aço Inox de altíssima gramatura", "Brilho permanente", "Design anatômico"],
    specs: { "Peças": "42 peças", "Material": "Aço Inox", "Garantia": "10 anos" },
    product_images: [
      { id: "img-tal-02-1", url: "https://images.unsplash.com/photo-1579781354160-d9e12e4e2a8a?auto=format&fit=crop&w=1000&q=85", alt: "Faqueiro em Aço Inox NEXLAR Gourmet 42 Peças", position: 0 },
      { id: "img-tal-02-2", url: "https://images.unsplash.com/photo-1573821663912-569905455b1c?auto=format&fit=crop&w=1000&q=85", alt: "Detalhe dos talheres", position: 1 },
    ],
  },
  {
    id: "prod-tal-03",
    name: "Bandeja de Servir em Aço Inox NEXLAR Espelhada 40x25cm",
    slug: "bandeja-de-servir-em-aco-inox-nexlar-espelhada-40x25cm",
    sku: "NX-5002400",
    short_description: "Bandeja retangular com alças anatômicas e bordas anti-queda em aço inox polido.",
    description: "Sirva cafés, drinks e petiscos com requinte e elegância. Acabamento espelhado de alto brilho e alças embutidas confortáveis.",
    category_id: "cat-mesa",
    categories: { name: "Mesa & Talheres", slug: "mesa-e-talheres" },
    price: 89.90,
    compare_at_price: 119.90,
    pix_discount_percent: 10,
    stock: 45,
    rating: 4.8,
    reviews_count: 67,
    free_shipping: false,
    featured: false,
    is_new: false,
    active: true,
    created_at: "2026-09-12T10:00:00Z",
    highlights: ["Acabamento inox espelhado", "Alças laterais anatômicas", "Bordas anti-derramamento", "Fácil higienização"],
    specs: { "Dimensões": "40 x 25 x 3 cm", "Material": "Aço Inox", "Garantia": "2 anos" },
    product_images: [
      { id: "img-tal-03-1", url: "https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?auto=format&fit=crop&w=1000&q=85", alt: "Bandeja de Servir em Aço Inox NEXLAR", position: 0 },
      { id: "img-tal-03-2", url: "https://images.unsplash.com/photo-1608835291093-394b0c943a75?auto=format&fit=crop&w=1000&q=85", alt: "Bandeja com serviço de café", position: 1 },
    ],
  },

  // ================= 7. ASSADEIRAS & FORMAS =================
  {
    id: "prod-ass-01",
    name: "Kit de Assadeiras Antiaderentes NEXLAR Bakeware 3 Peças",
    slug: "kit-de-assadeiras-antiaderentes-nexlar-bakeware-3-pecas",
    sku: "NX-1481300",
    short_description: "Conjunto com 3 assadeiras retangulares (P, M e G) com duplo revestimento antiaderente.",
    description: "Asse bolos, tortas, carnes e legumes sem grudar na forma. Distribui o calor perfeitamente para assados dourados e crocantes.",
    category_id: "cat-assadeiras",
    categories: { name: "Assadeiras & Formas", slug: "assadeiras-e-formas" },
    price: 149.90,
    compare_at_price: 199.90,
    pix_discount_percent: 10,
    stock: 45,
    rating: 4.8,
    reviews_count: 134,
    free_shipping: false,
    featured: true,
    is_new: false,
    active: true,
    created_at: "2026-09-16T10:00:00Z",
    highlights: ["3 tamanhos práticos que cabem em todos os fornos", "Antiaderente reforçado de fácil desmolde", "Suporta temperaturas de até 260°C", "Abas ergonômicas"],
    specs: { "Dimensões": "P (28x18cm), M (33x23cm), G (38x27cm)", "Material": "Aço carbono com antiaderente", "Garantia": "2 anos" },
    product_images: [
      { id: "img-ass-01-1", url: "https://images.unsplash.com/photo-1555949258-eb67b1ef0ceb?auto=format&fit=crop&w=1000&q=85", alt: "Kit de Assadeiras Antiaderentes NEXLAR Bakeware 3 Peças", position: 0 },
      { id: "img-ass-01-2", url: "https://images.unsplash.com/photo-1614148644219-5d36f6f011fc?auto=format&fit=crop&w=1000&q=85", alt: "Assadeira com bolo no forno", position: 1 },
    ],
  },
  {
    id: "prod-ass-02",
    name: "Forma de Bolo com Fundo Removível NEXLAR Springform 24cm",
    slug: "forma-de-bolo-com-fundo-removivel-nexlar-springform-24cm",
    sku: "NX-1481240",
    short_description: "Trava lateral springform e fundo texturizado para desenformar bolos e cheesecakes intactos.",
    description: "Desenforme suas sobremesas sem quebrar. A trava de liberação rápida abre a lateral com facilidade sem tocar na massa.",
    category_id: "cat-assadeiras",
    categories: { name: "Assadeiras & Formas", slug: "assadeiras-e-formas" },
    price: 59.90,
    compare_at_price: 79.90,
    pix_discount_percent: 10,
    stock: 70,
    rating: 4.8,
    reviews_count: 91,
    free_shipping: false,
    featured: false,
    is_new: false,
    active: true,
    created_at: "2026-09-13T10:00:00Z",
    highlights: ["Sistema springform de abertura lateral rápida", "Vedação anti-vazamento", "Duplo antiaderente interno e externo", "Fundo texturizado"],
    specs: { "Diâmetro": "24 cm", "Altura": "7 cm", "Material": "Aço carbono antiaderente", "Garantia": "12 meses" },
    product_images: [
      { id: "img-ass-02-1", url: "https://images.unsplash.com/photo-1555944956-30e4b9b8df5a?auto=format&fit=crop&w=1000&q=85", alt: "Forma de Bolo com Fundo Removível NEXLAR", position: 0 },
      { id: "img-ass-02-2", url: "https://images.unsplash.com/photo-1555949258-eb67b1ef0ceb?auto=format&fit=crop&w=1000&q=85", alt: "Bolo desenformado", position: 1 },
    ],
  },

  // ================= 8. ORGANIZAÇÃO =================
  {
    id: "prod-org-01",
    name: "Porta-Temperos Giratório em Inox NEXLAR Spices 12 Frascos",
    slug: "porta-temperos-giratorio-em-inox-nexlar-spices-12-frascos",
    sku: "NX-9001120",
    short_description: "Base giratória 360° em aço inox com 12 frascos de vidro herméticos e dosadores duplos.",
    description: "Tenha todas as especiarias e ervas organizadas e ao alcance da mão. Design compacto e sofisticado que valoriza qualquer bancada de cozinha.",
    category_id: "cat-organizacao",
    categories: { name: "Organização", slug: "organizacao" },
    price: 119.90,
    compare_at_price: 159.90,
    pix_discount_percent: 10,
    stock: 45,
    rating: 4.9,
    reviews_count: 148,
    free_shipping: false,
    featured: true,
    is_new: false,
    active: true,
    created_at: "2026-09-17T10:00:00Z",
    highlights: ["Giro suave em 360 graus", "12 frascos de vidro borossilicato transparente", "Tampas dosadoras finas e grossas em inox", "Aço inox escovado"],
    specs: { "Frascos": "12 unidades de 100ml cada", "Material": "Aço Inox e Vidro", "Garantia": "2 anos" },
    product_images: [
      { id: "img-org-01-1", url: "https://images.unsplash.com/photo-1556228578-8c89e6adf883?auto=format&fit=crop&w=1000&q=85", alt: "Porta-Temperos Giratório NEXLAR Inox 12 Frascos", position: 0 },
      { id: "img-org-01-2", url: "https://images.unsplash.com/photo-1493606278519-11aa9f86e40a?auto=format&fit=crop&w=1000&q=85", alt: "Frascos de condimentos organizados", position: 1 },
    ],
  },
  {
    id: "prod-org-02",
    name: "Conjunto de Potes Herméticos NEXLAR ClearLock 10 Peças",
    slug: "conjunto-de-potes-hermeticos-nexlar-clearlock-10-pecas",
    sku: "NX-9002100",
    short_description: "Acrílico crystal ultra resistente com travas 100% herméticas que conservam alimentos por muito mais tempo.",
    description: "Organização impecável para armários, despensas e geladeiras. Vedação a vácuo com anel de silicone contra umidade e insetos.",
    category_id: "cat-organizacao",
    categories: { name: "Organização", slug: "organizacao" },
    price: 199.90,
    compare_at_price: 259.90,
    pix_discount_percent: 10,
    stock: 40,
    rating: 4.9,
    reviews_count: 192,
    free_shipping: true,
    featured: true,
    is_new: true,
    active: true,
    created_at: "2026-09-18T10:00:00Z",
    highlights: ["Vedação com anel de silicone 100% hermético", "Acrílico crystal livre de BPA", "Empilhamento inteligente que economiza espaço", "Fácil higienização"],
    specs: { "Volumes": "2x 1.9L, 2x 1.2L, 3x 800ml, 3x 500ml", "Material": "Acrílico SAN e Silicone", "Garantia": "2 anos" },
    product_images: [
      { id: "img-org-02-1", url: "https://images.unsplash.com/photo-1493606278519-11aa9f86e40a?auto=format&fit=crop&w=1000&q=85", alt: "Conjunto de Potes Herméticos NEXLAR ClearLock", position: 0 },
      { id: "img-org-02-2", url: "https://images.unsplash.com/photo-1556228578-8c89e6adf883?auto=format&fit=crop&w=1000&q=85", alt: "Despensa organizada com potes herméticos", position: 1 },
    ],
  },

  // ================= 9. CHURRASCO =================
  {
    id: "prod-chr-01",
    name: "Kit Churrasco em Aço Inox NEXLAR Fire Master 5 Peças com Maleta",
    slug: "kit-churrasco-em-aco-inox-nexlar-fire-master-5-pecas-maleta",
    sku: "NX-1001050",
    short_description: "Faca 8\", garfo trinchante, pegador longo, espátula multiúso e pincel em maleta rígida de alumínio.",
    description: "O conjunto completo para mestres churrasqueiros. Utensílios em aço inox de alta espessura com comprimento extra para proteger do calor da brasa.",
    category_id: "cat-churrasco",
    categories: { name: "Churrasco", slug: "churrasco" },
    price: 279.90,
    compare_at_price: 359.90,
    pix_discount_percent: 10,
    stock: 30,
    rating: 4.9,
    reviews_count: 95,
    free_shipping: true,
    featured: true,
    is_new: false,
    active: true,
    created_at: "2026-09-17T10:00:00Z",
    highlights: ["Aço Inox maciço de alta resistência", "Cabo longo com proteção antitérmica", "Maleta rígida em alumínio com travas", "Fio de faca com têmpera especial"],
    specs: { "Itens": "Faca 8\", garfo, espátula vazada, pegador, pincel de silicone, maleta", "Material": "Aço Inox e Alumínio", "Garantia": "3 anos" },
    product_images: [
      { id: "img-chr-01-1", url: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=1000&q=85", alt: "Kit Churrasco NEXLAR Fire Master com Maleta", position: 0 },
      { id: "img-chr-01-2", url: "https://images.unsplash.com/photo-1529692236671-f1f6cf9683ba?auto=format&fit=crop&w=1000&q=85", alt: "Utensílios de churrasco na brasa", position: 1 },
    ],
  },
  {
    id: "prod-chr-02",
    name: "Grelha Argentina em Aço Inox NEXLAR Parrilla 60x40cm com Calha",
    slug: "grelha-argentina-em-aco-inox-nexlar-parrilla-60x40cm-calha",
    sku: "NX-1002600",
    short_description: "Canaletas em 'V' com inclinação que recolhem a gordura evitando fumaça e labaredas na carne.",
    description: "A autêntica grelha argentina Parrilla: grelha as carnes suculentas sem queimá-las por respingos de gordura no carvão.",
    category_id: "cat-churrasco",
    categories: { name: "Churrasco", slug: "churrasco" },
    price: 349.90,
    compare_at_price: 449.90,
    pix_discount_percent: 10,
    stock: 20,
    rating: 4.8,
    reviews_count: 59,
    free_shipping: true,
    featured: false,
    is_new: false,
    active: true,
    created_at: "2026-09-14T10:00:00Z",
    highlights: ["Canaletas em V com leve inclinação", "Reservatório coletor de gordura removível", "Aço Inox 304 que não enferruja", "Cabos em madeira tratada"],
    specs: { "Área útil": "60 x 40 cm", "Material": "Aço Inox 304 espessura 1.5mm", "Garantia": "5 anos" },
    product_images: [
      { id: "img-chr-02-1", url: "https://images.unsplash.com/photo-1529692236671-f1f6cf9683ba?auto=format&fit=crop&w=1000&q=85", alt: "Grelha Argentina Inox NEXLAR", position: 0 },
      { id: "img-chr-02-2", url: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=1000&q=85", alt: "Churrasco sendo preparado na grelha", position: 1 },
    ],
  },
];

// Funções de acesso rápido
export function getLocalCategories(): Category[] {
  return [...CATEGORIES].sort((a, b) => a.position - b.position);
}

export function getLocalCategoryBySlug(slug: string): Category | undefined {
  return CATEGORIES.find((c) => c.slug === slug);
}

export function getLocalBanners(): Banner[] {
  return [...BANNERS].sort((a, b) => a.position - b.position);
}

export function getLocalProducts(filter?: "featured" | "new" | "offers"): Product[] {
  let list = PRODUCTS.filter((p) => p.active);
  if (filter === "featured") list = list.filter((p) => p.featured);
  if (filter === "new") list = list.filter((p) => p.is_new);
  if (filter === "offers") list = list.filter((p) => p.compare_at_price && p.compare_at_price > p.price);
  return list;
}

export function getLocalProductsByCategory(categorySlugOrId: string): Product[] {
  const cat = CATEGORIES.find((c) => c.slug === categorySlugOrId || c.id === categorySlugOrId);
  if (!cat) return [];
  return PRODUCTS.filter((p) => p.category_id === cat.id || p.categories?.slug === cat.slug);
}

export function getLocalProductBySlug(slug: string): Product | undefined {
  return PRODUCTS.find((p) => p.slug === slug);
}

export function searchLocalProducts(term: string): Product[] {
  const q = term.toLowerCase().trim();
  if (!q) return [];
  return PRODUCTS.filter(
    (p) =>
      p.name.toLowerCase().includes(q) ||
      p.short_description?.toLowerCase().includes(q) ||
      p.categories?.name.toLowerCase().includes(q) ||
      p.highlights.some((h) => h.toLowerCase().includes(q)),
  );
}
